### ISSUE TITLE
Example project can't find wrappers.proto

### ISSUE THREAD

**Issue by alexklibisz** [scalapb/ScalaPB#1061]
I cloned master and made added an import for `wrappers.proto` in `examples/basic/src/main/protobuf/addressbook.proto`:

```
diff --git a/examples/basic/src/main/protobuf/addressbook.proto b/examples/basic/src/main/protobuf/addressbook.proto
index 958f7213..b7d713cc 100644
--- a/examples/basic/src/main/protobuf/addressbook.proto
+++ b/examples/basic/src/main/protobuf/addressbook.proto
@@ -2,6 +2,8 @@ syntax = "proto2";
 
 package tutorial;
 
+import "google/protobuf/wrappers.proto";
+
 message Person {
   required string name = 1;
   required int32 id = 2;
```

Then when I run `protocGenerate` I get the following error:

```
sbt -batch protocGenerate             
Copying runtime jar.
[info] welcome to sbt 1.4.0 (Ubuntu Java 11.0.9.1)
[info] loading global plugins from /home/alex/.sbt/1.0/plugins
[info] loading settings for project basic-build from plugins.sbt ...
[info] loading project definition from /tmp/ScalaPB/examples/basic/project
[info] loading settings for project basic from build.sbt ...
[info] set current project to basic (in build file:/tmp/ScalaPB/examples/basic/)
[info] Compiling 1 protobuf files to /tmp/ScalaPB/examples/basic/target/scala-2.13/src_managed/main/scalapb
[info] Compiling schema /tmp/ScalaPB/examples/basic/src/main/protobuf/addressbook.proto
protoc-jar: protoc version: 3.11.4, detected platform: linux-x86_64 (linux/amd64)
protoc-jar: embedded: bin/3.11.4/protoc-3.11.4-linux-x86_64.exe
protoc-jar: executing: [/tmp/protocjar7608681234981052233/bin/protoc.exe, --plugin=protoc-gen-jvm_0=/tmp/protocbridge7370582362450334031, --jvm_0_out=/tmp/ScalaPB/examples/basic/target/scala-2.13/src_managed/main/scalapb, -I/tmp/ScalaPB/examples/basic/src/main/protobuf, -I/tmp/ScalaPB/examples/basic/target/protobuf_external_src, -I/tmp/ScalaPB/examples/basic/target/protobuf_external, /tmp/ScalaPB/examples/basic/src/main/protobuf/addressbook.proto]
google/protobuf/wrappers.proto: File not found.
addressbook.proto:5:1: Import "google/protobuf/wrappers.proto" was not found or had errors.
[error] java.lang.RuntimeException: protoc returned exit code: 1
[error] 	at scala.sys.package$.error(package.scala:30)
[error] 	at sbtprotoc.ProtocPlugin$.compile(ProtocPlugin.scala:343)
[error] 	at sbtprotoc.ProtocPlugin$.compileProto$1(ProtocPlugin.scala:431)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$10(ProtocPlugin.scala:438)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:80)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:153)
[error] 	at sbt.util.Difference.apply(Tracked.scala:414)
[error] 	at sbt.util.Difference.apply(Tracked.scala:394)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:149)
[error] 	at sbt.util.Difference.apply(Tracked.scala:414)
[error] 	at sbt.util.Difference.apply(Tracked.scala:389)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:148)
[error] 	at sbtprotoc.ProtocPlugin$.$anonfun$sourceGeneratorTask$4(ProtocPlugin.scala:443)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:68)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:282)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:23)
[error] 	at sbt.Execute.work(Execute.scala:291)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:282)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:265)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:64)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Compile / protocGenerate) protoc returned exit code: 1
[error] Total time: 1 s, completed Feb 7, 2021, 6:39:01 PM
```

I'm also seeing this same issue in a larger project. I've definitely gotten these examples working with google's wrappers.proto in the past. Not sure what has changed. I appreciate any tips.

**Comment by alexklibisz** [comment]
As it goes, I found the solution ~60 minutes after finding the bug and ~30 seconds after posting the issue. :)

```
// (optional) If you need scalapb/scalapb.proto or anything from
// google/protobuf/*.proto
libraryDependencies ++= Seq(
    "com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"
)
```

from https://scalapb.github.io/docs/installation
