### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.<init>

### ISSUE THREAD

**Issue by Vishvin95** [scalapb/ScalaPB#1078]
Using Apache Spark 3.0, when trying to read Azure Event Hub source with following dependencies in SBT, it gives the following exception:
``
java.lang.NoSuchMethodError: org.apache.spark.sql.catalyst.encoders.ExpressionEncoder.<init>(Lorg/apache/spark/sql/types/StructType;ZLscala/collection/Seq;Lorg/apache/spark/sql/catalyst/expressions/Expression;Lscala/reflect/ClassTag;)V
	at frameless.TypedExpressionEncoder$.apply(TypedExpressionEncoder.scala:45)
	at scalapb.spark.Implicits.typedEncoderToEncoder(TypedEncoders.scala:125)
	at scalapb.spark.Implicits.typedEncoderToEncoder$(TypedEncoders.scala:122)
	at scalapb.spark.Implicits$.typedEncoderToEncoder(TypedEncoders.scala:128)
	at Utils.MessagingQueues.EventHubSourceReader$.editorialAdStream(EventHubSourceReader.scala:57)
	at Utils.MessagingQueues.SourceReader$.readEditorialAdSource(SourceReader.scala:39)
	at Workflows.Streaming.PROD.UnifiedNRT.UnifiedNRTHelper$.fetchInputStream(UnifiedNRTHelper.scala:62)
	at Workflows.Streaming.PROD.UnifiedNRT.UnifiedNRT$.main(UnifiedNRT.scala:50)
	at Workflows.Streaming.PROD.UnifiedNRT.UnifiedNRT.main(UnifiedNRT.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
``

Dependencies:
``
 "com.google.protobuf" %% "protobuf-java-util" % "3.11.1",
 "com.thesamet.scalapb" %% "sparksql-scalapb" % "0.10.4",
 "com.thesamet.scalapb" %% "scalapb-json4s" % "0.9.3",
 "com.thesamet.scalapb" %% "compilerplugin" % "0.9.4"
``

**Comment by thesamet** [comment]
Please see the [version compatibility matrix](https://scalapb.github.io/docs/sparksql/#setting-up-your-project). To use spark 3 you need to update sparksql-scalapb to 0.11.0-RC1
