### ISSUE TITLE
NullPointerException in __computeSerializedValue

### ISSUE THREAD

**Issue by mingyu89** [scalapb/ScalaPB#1702]
Hello, I encountered the same issue as this old one https://github.com/scalapb/ScalaPB/issues/249 with a similar stacktrace.
```
java.lang.NullPointerException: null
	at MyMessage.__computeSerializedValue(MyMessage.scala:130) ~[classes/:?]
	at MyMessage.serializedSize(MyMessage.scala:137) ~[classes/:?]
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray(GeneratedMessageCompanion.scala:93) ~[scalapb-runtime_2.12-0.5.47.jar:0.5.47]
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray$(GeneratedMessageCompanion.scala:92) ~[scalapb-runtime_2.12-0.5.47.jar:0.5.47]
	at MyMessage.toByteArray(MyMessage.scala:20) ~[classes/:?]
```
The generated code should check both `null` value and `isDefined`.

Steps to reproduce:
1. Create a proto message `message1` with string field `field1`.
2. Serialize a `message1` object `o1` into byte array.
3. Update the proto message `message1` and add a new string field `field2`
4. Deserialize object `o1` using the update `message1`.

**Comment by thesamet** [comment]
It seems like you are using a very old version of scalapb. Can you try with a recent version? The specific scenario you described should not result in NPE.

**Comment by thesamet** [comment]
Closing due to inactivity.
