### ISSUE TITLE
When repeat field is empty, GeneratedMessage's toString will throw NullPointerException

### ISSUE THREAD

**Issue by gebing** [scalapb/ScalaPB#178]
I have a object of GeneratedMessage with repeat field, and its content is empty, when i call object's toString, it throws NullPointerException. Below is the exception message:

```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
    at com.trueaccord.scalapb.textformat.Printer$.print(Printer.scala:11)
    at com.trueaccord.scalapb.textformat.Printer$.printFieldValue(Printer.scala:80)
    at com.trueaccord.scalapb.textformat.Printer$.printSingleField(Printer.scala:38)
    at com.trueaccord.scalapb.textformat.Printer$$anonfun$printField$1.apply(Printer.scala:25)
    at com.trueaccord.scalapb.textformat.Printer$$anonfun$printField$1.apply(Printer.scala:25)
    at scala.collection.Iterator$class.foreach(Iterator.scala:893)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
    at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    at com.trueaccord.scalapb.textformat.Printer$.printField(Printer.scala:24)
    at com.trueaccord.scalapb.textformat.Printer$$anonfun$print$2.apply(Printer.scala:13)
    at com.trueaccord.scalapb.textformat.Printer$$anonfun$print$2.apply(Printer.scala:11)
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
    at com.trueaccord.scalapb.textformat.Printer$.print(Printer.scala:11)
    at com.trueaccord.scalapb.textformat.Printer$.printToString(Printer.scala:19)
    at com.trueaccord.scalapb.TextFormat$.printToSingleLineUnicodeString(TextFormat.scala:38)

```

I study the source code of ScalaPB, it is caused in this function and 't' is null:

```
object Printer {
  def print(t: GeneratedMessage, out: TextGenerator): Unit = {
    t.getAllFields.toSeq.sortBy(_._1.getNumber).foreach {
      case (fd, value) =>
        printField(fd, value, out)
    }
  }
```

**Comment by thesamet** [comment]
It looks like you are calling toString() on a null value. Can you provide a minimal example where this happens?

**Comment by thesamet** [comment]
@gebing - closing due to inactivity - feel free post an example here if this still occurs.
