### ISSUE TITLE
NotImplementedError on ScalaJs

### ISSUE THREAD

**Issue by mlvn23** [scalapb/ScalaPB#187]
In ScalaJs, whenever I tried to do a println or toString on a ScalaPB-generated case class, I'm getting a NotImplementedError. I think it has something to do with the descriptor. I tried to run the [scalapbjs-Test](https://github.com/thesamet/scalapbjs-test) example and I see the same issue.

Here's the stack trace:

```
Predef.scala:252 Uncaught $c_s_NotImplementedErrore$1: nulls$1: "an implementation is missing"stack: "Error↵    at $c_s_NotImplementedError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:10532:14)↵    at $c_s_NotImplementedError.$c_jl_Throwable.init___T__jl_Throwable (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:10548:8)↵    at $c_s_NotImplementedError.init___ (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:17499:52)↵    at $c_s_Predef$.$$qmark$qmark$qmark__sr_Nothing$ (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:10761:40)↵    at $c_Lcom_trueaccord_foods_FoodsProto$.descriptor$lzycompute__p1__Lcom_google_protobuf_Descriptors$FileDescriptor (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:4908:592)↵    at $c_Lcom_trueaccord_foods_FoodsProto$.descriptor__Lcom_google_protobuf_Descriptors$FileDescriptor (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:4904:37)↵    at $c_Lcom_trueaccord_foods_Menu$.descriptor__Lcom_google_protobuf_Descriptors$Descriptor (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:16719:97)↵    at $s_Lcom_trueaccord_scalapb_GeneratedMessage$class__getAllFields__Lcom_trueaccord_scalapb_GeneratedMessage__sci_Map (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:1065:81)↵    at $c_Lcom_trueaccord_scalapb_textformat_Printer$.print__Lcom_trueaccord_scalapb_GeneratedMessage__Lcom_trueaccord_scalapb_textformat_TextGenerator__V (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:5567:16)↵    at $c_Lcom_trueaccord_scalapb_textformat_Printer$.printToString__Lcom_trueaccord_scalapb_GeneratedMessage__Z__Z__T (file:///D:/sw-dev/scalajs/scalapbjs-test/target/scala-2.10/scalapb-on-scalajs-demo-fastopt.js:5561:8)"stackTrace$1: nullstackdata: $c_s_NotImplementedError__proto__: $c_jl_Error$c_s_Predef$.$$qmark$qmark$qmark__sr_Nothing$ @ Predef.scala:252$c_Lcom_trueaccord_foods_FoodsProto$.descriptor$lzycompute__p1__Lcom_google_protobuf_Descriptors$FileDescriptor @ FoodsProto.scala:11$c_Lcom_trueaccord_foods_FoodsProto$.descriptor__Lcom_google_protobuf_Descriptors$FileDescriptor @ FoodsProto.scala:11$c_Lcom_trueaccord_foods_Menu$.descriptor__Lcom_google_protobuf_Descriptors$Descriptor @ Menu.scala:92$s_Lcom_trueaccord_scalapb_GeneratedMessage$class__getAllFields__Lcom_trueaccord_scalapb_GeneratedMessage__sci_Map @ GeneratedMessageCompanion.scala:79$c_Lcom_trueaccord_scalapb_textformat_Printer$.print__Lcom_trueaccord_scalapb_GeneratedMessage__Lcom_trueaccord_scalapb_textformat_TextGenerator__V @ Printer.scala:11$c_Lcom_trueaccord_scalapb_textformat_Printer$.printToString__Lcom_trueaccord_scalapb_GeneratedMessage__Z__Z__T @ Printer.scala:19$c_Lcom_trueaccord_FoodProtoDemo$.updateRightSide$1__p1__Lcom_trueaccord_foods_Menu__Lorg_scalajs_dom_raw_HTMLPreElement__Lorg_scalajs_dom_raw_HTMLPreElement__V @ FoodProtoDemo.scala:18$c_Lcom_trueaccord_FoodProtoDemo$.main__Lorg_scalajs_dom_raw_HTMLDivElement__Lorg_scalajs_dom_raw_Node @ FoodProtoDemo.scala:50$c_Lcom_trueaccord_FoodProtoDemo$.$$js$exported$meth$main__Lorg_scalajs_dom_raw_HTMLDivElement__O @ FoodProtoDemo.scala:12$c_Lcom_trueaccord_FoodProtoDemo$.main @ FoodProtoDemo.scala:12(anonymous function) @ index-dev.html:23
```

**Comment by thesamet** [comment]
This is fixed on 0.6.0-pre1 - live demo has been updated: http://thesamet.github.io/scalapbjs-test/
