### ISSUE TITLE
JavaDescriptor AbstractMethodErrot

### ISSUE THREAD

**Issue by ayyappanramamuniappa** [scalapb/ScalaPB#226]
Got a question? Please use https://groups.google.com/forum/#!forum/scalapb instead.

I am trying to convert GeneratedMessage to Json. I am getting the following error. 
```
java.lang.AbstractMethodError: models.pricing.test.TestHotelResult$.javaDescriptor()Lcom/google/protobuf/Descriptors$Descriptor;
[error] 	at com.trueaccord.scalapb.GeneratedMessage$class.getAllFields(GeneratedMessageCompanion.scala:76)
[error] 	at models.pricing.test.TestHotelResult.getAllFields(TestHotelResultProto.scala:11)
[error] 	at com.trueaccord.scalapb.textformat.Printer$.print(Printer.scala:11)
[error] 	at com.trueaccord.scalapb.textformat.Printer$.printToString(Printer.scala:19)
[error] 	at com.trueaccord.scalapb.TextFormat$.printToUnicodeString(TextFormat.scala:34)
[error] 	at models.pricing.test.TestHotelResult.toString(TestHotelResultProto.scala:61)
[error] 	at api.routing.routes.TestRoute$$anonfun$testRoute$1$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$45$$anonfun$apply$46.apply(PropertyRoute.scala:304)
[error] 	at api.routing.routes.TestRoute$$anonfun$testRoute$1$$anonfun$apply$42$$anonfun$apply$43$$anonfun$apply$45$$anonfun$apply$46.apply(PropertyRoute.scala:304)
[error] 	at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:49)
[error] 	at spray.routing.directives.RouteDirectives$$anonfun$complete$1$$anon$3.apply(RouteDirectives.scala:48)
[error] 	at spray.routing.directives.OnSuccessFutureMagnet$$anon$2$$anonfun$happly$2$$anonfun$apply$2.apply(FutureDirectives.scala:81)
[error] 	at spray.routing.directives.OnSuccessFutureMagnet$$anon$2$$anonfun$happly$2$$anonfun$apply$2.apply(FutureDirectives.scala:79)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
[error] 	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
[error] 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
[error] 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
[error] 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

But I have checked the generated Scala code and they do have the descriptor overridden. 

Is this one of the known issues?

**Comment by thesamet** [comment]
Which version of ScalaPB are you using? Can you try both 0.5.47 and 0.5.46?

**Comment by ayyappanramamuniappa** [comment]
I am using 0.5.46. The default unmarshaller in scalapb serializes allFields in the GeneratedMessage. So the json has the case class fields and also the allFields which has all the fields in the class. I tried using scalapb-json4s. I am getting this error when I use scalapb-json4s.

**Comment by ayyappanramamuniappa** [comment]
I am using 0.5.47 and now it is working. Thanks.
