### ISSUE TITLE
Scala.js Any.pack leads to scala.NotImplementedError: an implementation is missing

### ISSUE THREAD

**Issue by Unmoving** [scalapb/ScalaPB#238]
I am trying to send a message with a wrapped `google.protobuf.Any` over the wire (`Scala.js` client), but no luck so far:

```
syntax = "proto3";
import "google/protobuf/any.proto";

message Message
{
   google.protobuf.Any message = 1;
}

message Auth
{
    string user = 1;
}
```

```
    val auth = Auth().withUser("test")
    val msg = Message().withMessage(Any.pack(auth))

    val bytes: Array[Byte] = msg.toByteArray
    dom.window.console.log(bytes.length)
    val jsByteArray = new Uint8Array(bytes.length) // TODO find out whether Uint8Array is always enough
    for ((data, index) <- bytes.view.zipWithIndex)
      jsByteArray(index) = data

    jsByteArray.buffer
```

If I just use `val msg = Message()` or `val msg = Auth().withUser("test")` everything works just fine, but not with `Any.pack`. Why is that? Is this implementation in Scala.js missing?

**Comment by thesamet** [comment]
Looks like something is indeed missing. Can you provide stack trace?

**Comment by RookieMaus** [comment]
Will try to. Don't see one in JavaScript in Mozilla dev tools and `console.trace();` does not give me anything (useful) at all. But then again, I have not debugged JavaScript before.

**Comment by RookieMaus** [comment]
No idea how to provide additional info, sorry. StackTrace in Firefox and Chromium looks empty and wrapping code in a try and

      ```
 catch
          {
            case e => dom.window.console.log("error")
              e
          }
```

leads to nothing

**Comment by RookieMaus** [comment]
That's all I can find and it's useless to me, but maybe it helps you:

`"Error
    at $c_s_NotImplementedError.$c_jl_Throwable.fillInStackTrace__jl_Throwable (http://localhost:9000/assets/client-fastopt-bundle.js:10831:15)
    at $c_s_NotImplementedError.$c_jl_Throwable.init___T__jl_Throwable (http://localhost:9000/assets/client-fastopt-bundle.js:10847:9)
    at $c_s_NotImplementedError.init___ (http://localhost:9000/assets/client-fastopt-bundle.js:17222:53)
    at $c_s_Predef$.$$qmark$qmark$qmark__sr_Nothing$ (http://localhost:9000/assets/client-fastopt-bundle.js:14828:41)
    at $c_Ltld_project_proto_Message_MessageProto$.javaDescriptor$lzycompute__p1__Lcom_google_protobuf_Descriptors$FileDescriptor (http://localhost:9000/assets/client-fastopt-bundle.js:4862:533)
    at $c_Ltld_project_proto_Message_MessageProto$.javaDescriptor__Lcom_google_protobuf_Descriptors$FileDescriptor (http://localhost:9000/assets/client-fastopt-bundle.js:4858:38)
    at $c_Ltld_project_proto_Message_Auth$.javaDescriptor__Lcom_google_protobuf_Descriptors$Descriptor (http://localhost:9000/assets/client-fastopt-bundle.js:16679:105)
    at $f_Lcom_trueaccord_scalapb_AnyCompanionMethods__pack__Lcom_trueaccord_scalapb_GeneratedMessage__T__Lcom_google_protobuf_any_Any (http://localhost:9000/assets/client-fastopt-bundle.js:1107:178)
    at $c_Ltld_project_WSocketCaller$.prepareData__p1__sjs_js_typedarray_ArrayBuffer (http://localhost:9000/assets/client-fastopt-bundle.js:4789:98)
    at $c_Ltld_project_WSocketCaller$.tld$project$WSocketCaller$$$anonfun$call$1__Lorg_scalajs_dom_raw_Event__Lorg_scalajs_dom_raw_WebSocket__V (http://localhost:9000/assets/client-fastopt-bundle.js:4820:17)"`

**Comment by thesamet** [comment]
Looks like Any uses `javaDescriptors` (https://github.com/scalapb/ScalaPB/blob/f0e1ddc5728f140667a322563c3e600e79530f51/scalapb-runtime/shared/src/main/scala/com/trueaccord/scalapb/AnyMethods.scala#L33) which are not available in ScalaJS (since they are in Java). Soon we are going to have a release that adds a Scala native implementation of descriptors which would resolve this.

**Comment by RookieMaus** [comment]
Awwww :( But thanks! Is there a beta-version anywhere I could try out already? I would self-compile (as long as I somehow find out how to shadow the compiler to get `compilerplugin-shaded` version of the plugin - if necessary)

**Comment by thesamet** [comment]
Sorry, not yet. I hope that by this time next week I have something.

**Comment by RookieMaus** [comment]
no big deal. Trying to work around this with `bytes`, no luck so far. (Trying to encode the whole sub-message as `bytes` and then parsing it back from that)

**Comment by thesamet** [comment]
Reopening, since we still need to fix Any.
