### ISSUE TITLE
NullPointerException in __computeSerializedValue

### ISSUE THREAD

**Issue by analytically** [scalapb/ScalaPB#249]
```
java.lang.NullPointerException: null
	at MyMessage.__computeSerializedValue(MyMessage.scala:130) ~[classes/:?]
	at MyMessage.serializedSize(MyMessage.scala:137) ~[classes/:?]
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray(GeneratedMessageCompanion.scala:93) ~[scalapb-runtime_2.12-0.5.47.jar:0.5.47]
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray$(GeneratedMessageCompanion.scala:92) ~[scalapb-runtime_2.12-0.5.47.jar:0.5.47]
	at MyMessage.toByteArray(MyMessage.scala:20) ~[classes/:?]
```

the line is

```
if (metadata.isDefined) { __size += 2 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(metadata.get.serializedSize) + metadata.get.serializedSize }
```

This metadata message is a proto3 `Metadata metadata = 998;`.

**Comment by analytically** [comment]
I believe the `if (metadata.isDefined)` should perhaps be `if (metadata != null && metadata.isDefined)`

**Comment by thesamet** [comment]
How did the null metadata field get in into the message you are serializing? ScalaPB doesn't expect nulls in fields, so if that field is null then this exception is to be expected.

**Comment by analytically** [comment]
I'm not setting the metadata field anywhere.

**Comment by thesamet** [comment]
So how do you instantiate the enclosing message then (or where do you get it from)?

**Comment by thesamet** [comment]
Closing due to inactivity. Feel free to let me know if you have additional information on how to reproduce this and I'll reopen. However, NPE is expected if nulls are present in the message case class being serialized.
