### ISSUE TITLE
Failed to stream message com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space

### ISSUE THREAD

**Issue by macalinao** [scalapb/ScalaPB#274]
This happens when I try to send a message that uses a `Set`.

```
sbt "runMain asuna.playground.MatchSumConsistencyCheck --alexandria_host=localhost --alexandria_port=22045 --vulgate_host=localhost --vulgate_port=6205"
[0m[[0minfo[0m] [0mLoading global plugins from /Users/ian/.sbt/0.13/plugins[0m
Installing the s3:// URLStreamHandler via java.net.URL.setURLStreamHandlerFactory
Creating a new Ivy URLHandlerDispatcher to handle s3:// URLs
[0m[[0minfo[0m] [0mLoading project definition from /Users/ian/proj/asunaio/playground/project[0m
The s3:// URLStreamHandler is already installed
Using the existing Ivy URLHandlerDispatcher to handle s3:// URLs
[0m[[0minfo[0m] [0mSet current project to asuna-playground (in build file:/Users/ian/proj/asunaio/playground/)[0m
[0m[[0minfo[0m] [0mCompiling 1 Scala source to /Users/ian/proj/asunaio/playground/target/scala-2.12/classes...[0m
[0m[[0minfo[0m] [0mRunning asuna.playground.MatchSumConsistencyCheck --alexandria_host=localhost --alexandria_port=22045 --vulgate_host=localhost --vulgate_port=6205[0m
16:51:52.909 [run-main-0] INFO  asuna.common.BaseService - asuna-playground version: 609b6b21039f67b3ebbaeff7a90ab2ae9cb552d4
16:51:54.616 [grpc-default-executor-0] ERROR asuna.common.BaseService - Downstream error from alexandria: Failed to stream message
com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.: Pos: 18, limit: 17, len: 1
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1349)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeInt32NoTag(CodedOutputStream.java:1314)
	at com.google.protobuf.CodedOutputStream.writeEnumNoTag(CodedOutputStream.java:464)
	at asuna.proto.league.MatchFiltersSpace.$anonfun$writeTo$10(MatchFiltersSpace.scala:131)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:206)
	at asuna.proto.league.MatchFiltersSpace.writeTo(MatchFiltersSpace.scala:131)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.$anonfun$writeTo$1(GetSumRequest.scala:36)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.$anonfun$writeTo$1$adapted(GetSumRequest.scala:33)
	at scala.Option.foreach(Option.scala:257)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.writeTo(GetSumRequest.scala:33)
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray(GeneratedMessageCompanion.scala:132)
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray$(GeneratedMessageCompanion.scala:129)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.toByteArray(GetSumRequest.scala:14)
	at com.trueaccord.scalapb.grpc.Marshaller.stream(Marshaller.scala:8)
	at com.trueaccord.scalapb.grpc.Marshaller.stream(Marshaller.scala:7)
	at io.grpc.MethodDescriptor.streamRequest(MethodDescriptor.java:258)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:393)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:67)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:251)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:186)
	at asuna.proto.league.alexandria.AlexandriaGrpc$AlexandriaStub.getSum(AlexandriaGrpc.scala:230)
	at asuna.playground.MatchSumConsistencyCheck$.$anonfun$main$2(MatchSumConsistencyCheck.scala:46)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 17
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1340)
	... 33 common frames omitted
[0m[[31merror[0m] [0m(run-main-0) io.grpc.StatusRuntimeException: INTERNAL: Downstream error from alexandria: Failed to stream message[0m
io.grpc.StatusRuntimeException: INTERNAL: Downstream error from alexandria: Failed to stream message
	at io.grpc.Status.asRuntimeException(Status.java:540)
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:439)
	at asuna.common.BaseService$$anon$2.onClose(BaseService.scala:90)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:428)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:514)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:431)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:546)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:152)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.: Pos: 18, limit: 17, len: 1
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1349)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeInt32NoTag(CodedOutputStream.java:1314)
	at com.google.protobuf.CodedOutputStream.writeEnumNoTag(CodedOutputStream.java:464)
	at asuna.proto.league.MatchFiltersSpace.$anonfun$writeTo$10(MatchFiltersSpace.scala:131)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:206)
	at asuna.proto.league.MatchFiltersSpace.writeTo(MatchFiltersSpace.scala:131)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.$anonfun$writeTo$1(GetSumRequest.scala:36)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.$anonfun$writeTo$1$adapted(GetSumRequest.scala:33)
	at scala.Option.foreach(Option.scala:257)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.writeTo(GetSumRequest.scala:33)
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray(GeneratedMessageCompanion.scala:132)
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray$(GeneratedMessageCompanion.scala:129)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.toByteArray(GetSumRequest.scala:14)
	at com.trueaccord.scalapb.grpc.Marshaller.stream(Marshaller.scala:8)
	at com.trueaccord.scalapb.grpc.Marshaller.stream(Marshaller.scala:7)
	at io.grpc.MethodDescriptor.streamRequest(MethodDescriptor.java:258)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:393)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:67)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:251)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:186)
	at asuna.proto.league.alexandria.AlexandriaGrpc$AlexandriaStub.getSum(AlexandriaGrpc.scala:230)
	at asuna.playground.MatchSumConsistencyCheck$.$anonfun$main$2(MatchSumConsistencyCheck.scala:46)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 17
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1340)
	at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeInt32NoTag(CodedOutputStream.java:1314)
	at com.google.protobuf.CodedOutputStream.writeEnumNoTag(CodedOutputStream.java:464)
	at asuna.proto.league.MatchFiltersSpace.$anonfun$writeTo$10(MatchFiltersSpace.scala:131)
	at scala.runtime.java8.JFunction1$mcVI$sp.apply(JFunction1$mcVI$sp.java:12)
	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
	at scala.collection.immutable.Set$Set4.foreach(Set.scala:206)
	at asuna.proto.league.MatchFiltersSpace.writeTo(MatchFiltersSpace.scala:131)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.$anonfun$writeTo$1(GetSumRequest.scala:36)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.$anonfun$writeTo$1$adapted(GetSumRequest.scala:33)
	at scala.Option.foreach(Option.scala:257)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.writeTo(GetSumRequest.scala:33)
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray(GeneratedMessageCompanion.scala:132)
	at com.trueaccord.scalapb.GeneratedMessage.toByteArray$(GeneratedMessageCompanion.scala:129)
	at asuna.proto.league.alexandria.rpc.GetSumRequest.toByteArray(GetSumRequest.scala:14)
	at com.trueaccord.scalapb.grpc.Marshaller.stream(Marshaller.scala:8)
	at com.trueaccord.scalapb.grpc.Marshaller.stream(Marshaller.scala:7)
	at io.grpc.MethodDescriptor.streamRequest(MethodDescriptor.java:258)
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:393)
	at io.grpc.ForwardingClientCall.sendMessage(ForwardingClientCall.java:67)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:251)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:186)
	at asuna.proto.league.alexandria.AlexandriaGrpc$AlexandriaStub.getSum(AlexandriaGrpc.scala:230)
	at asuna.playground.MatchSumConsistencyCheck$.$anonfun$main$2(MatchSumConsistencyCheck.scala:46)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:302)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[0m[[31mtrace[0m] [0mStack trace suppressed: run [34mlast compile:runMain[0m for the full output.[0m
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[0m[[31mtrace[0m] [0mStack trace suppressed: run [34mlast compile:runMain[0m for the full output.[0m
[0m[[31merror[0m] [0m(compile:[31mrunMain[0m) Nonzero exit code: 1[0m
[0m[[31merror[0m] [0mTotal time: 9 s, completed Apr 23, 2017 4:51:54 PM[0m

```

**Comment by macalinao** [comment]
Message looks like this

```
message MatchFiltersSpace {
  repeated uint32 champion_ids = 1 [(scalapb.field).collection_type = "Set"];
  repeated uint32 enemy_ids = 2 [(scalapb.field).collection_type = "Set"];
  repeated Region regions = 3 [(scalapb.field).collection_type = "Set"];
  repeated Role roles = 4 [(scalapb.field).collection_type = "Set"];
  repeated Tier tiers = 5 [(scalapb.field).collection_type = "Set"];
  repeated string versions = 6 [(scalapb.field).collection_type = "Set"];
  repeated Queue queues = 7 [(scalapb.field).collection_type = "Set"];
}
```

where all of those custom types are `enum`s.

**Comment by thesamet** [comment]
Seems like this is happening while serializing a `GetSumRequest`. Can you create a minimal example that demonstrates this? That is, protos and an instance of this message that triggers this exception once toByteArray is called on it.

**Comment by macalinao** [comment]
@thesamet https://github.com/macalinao/scalapb-set-example

**Comment by thesamet** [comment]
Thanks for providing the minimal example. There was a bug in summing up the sizes of the individual elements. This happens only for sets of primitives and enums that are packed (as in proto3). The problem was that for a set of numbers code like this does not work as expected: `numbers.map(computeSizeBytes).sum` - since we're calling `map` on a set, we are getting a *set* of sizes, rather than a list of sizes, so only unique sizes are summed.

**Comment by macalinao** [comment]
Interesting bug. Thanks for the fast resolution!

**Comment by macalinao** [comment]
do you know when the next scalapb may be published? We really want to use `Set`s in our protobufs.

**Comment by thesamet** [comment]
I'll update here - probably later today or tomorrow.

**Comment by thesamet** [comment]
0.6.0-pre4 has been released. It will be on maven central shortly.

**Comment by macalinao** [comment]
Thanks! 💯💯💯
