### ISSUE TITLE
Problem while compiling using Scala 2.12 on macOS

### ISSUE THREAD

**Issue by cemelo** [scalapb/ScalaPB#284]
When trying to compile via SBT, I got the following error.

Versions:
sbt-protoc - 0.99.8
compilerplugin-shaded - 0.6.0-pre4

```
java.lang.AbstractMethodError: scalapb.ScalaPbCodeGenerator$.registerExtensions(Lcom/google/protobuf/ExtensionRegistry;)V
	at protocbridge.frontend.PluginFrontend$.runWithBytes(PluginFrontend.scala:52)
	at protocbridge.frontend.PluginFrontend$.runWithInputStream(PluginFrontend.scala:67)
	at protocbridge.frontend.PosixPluginFrontend$$anonfun$prepare$1.apply$mcV$sp(PosixPluginFrontend.scala:25)
	at protocbridge.frontend.PosixPluginFrontend$$anonfun$prepare$1.apply(PosixPluginFrontend.scala:23)
	at protocbridge.frontend.PosixPluginFrontend$$anonfun$prepare$1.apply(PosixPluginFrontend.scala:23)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

 Am I missing some configuration or artifact?

**Comment by thesamet** [comment]
I've got another report last week that there's something broken with compilerplugin-shaded in recent versions. I'll look into this in the next few days. Are you using Spark/ScalaJS or anything that prevents you from using the non-shaded version?

**Comment by ngbinh** [comment]
hmm, I am using the same setup and everything works fine.

**Comment by cemelo** [comment]
@thesamet not really. I might add that I am using it in a multimodule project. When I use either `compilerplugin` or Scala 2.11 everything works fine.

**Comment by akauppi** [comment]
I had 2.12 specific problems yesterday, but when trying to isolate them and publish a public GitHub repo, they disappeared. 

That is, something in the simplification caused the problems to vanish. I'll let you know if I can trap them into a reproducible repo.

**Comment by thesamet** [comment]
@cemelo can you provide a minimal example that demonstrates this issue?

**Comment by cemelo** [comment]
@thesamet the same thing as with @akauppi happened to me. I'll try to create a project with the same configuration as when I first spotted the error and share it here with you.

**Comment by akauppi** [comment]
Just to let you know, I never saw those problems on the second problem, and am very happy currently with ScalaPB and Scala 2.12.

**Comment by cemelo** [comment]
@thesamet I think this problem has something to do with my env setup. After recreating the project (in IntelliJ, not rewriting from scratch), I didn't get that exception anymore. Since I didn't manage to reproduce it in a fresh project, I'll close this issue.

Anyways, thanks for jumping in.
