### ISSUE TITLE
MatchError when deserializing unknown enum value

### ISSUE THREAD

**Issue by avakhrenev** [scalapb/ScalaPB#285]
Relevant log entry:
```
scala.MatchError: Some(scala.ref.WeakReferenceWithWrapper@7429e9f7) (of class scala.Some)
  at scalapb.descriptors.ConcurrentWeakReferenceMap.getOrElseUpdate(ConcurrentWeakReferenceMap.scala:15)
  at scalapb.descriptors.EnumDescriptor.findValueByNumberCreatingIfUnknown(Descriptor.scala:115)
  at com.trueaccord.scalapb.UnrecognizedEnum.scalaValueDescriptor(GeneratedMessageCompanion.scala:44)
  at com.trueaccord.scalapb.UnrecognizedEnum.scalaValueDescriptor$(GeneratedMessageCompanion.scala:43)
```
`WeakReference.unapply` is `None` when referenced object is GC'ed, which isn't handled in `ConcurrentWeakReferenceMap`.

**Comment by avakhrenev** [comment]
That was fast. Thank you!
