### ISSUE TITLE
Streamed Response Causes Duplicate Headers

### ISSUE THREAD

**Issue by sammerry** [scalapb/ScalaPB#291]
# What version of gRPC are you using?
plugins.sbt
```
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.3")
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.6.0-pre4"
```
build.sbt
```
"com.trueaccord.scalapb" %% "scalapb-runtime" % scalapbVersion % "protobuf",
"com.trueaccord.scalapb" %% "scalapb-runtime-grpc" % scalapbVersion,
"io.grpc" % "grpc-netty" % "1.4.0",
```
# What JVM are you using (java -version)?
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

with scala 2.12

# The problem
When streaming back responses using the following rpc definition i occasionally get a duplicate headers exception.
```
service Mediation {

    // Sends a greeting
    rpc StreamMediate (HelloRequest) returns (stream HelloResponse) {}
}
```

Randomly around every 10th run will trigger this exception.
```
io.grpc.StatusRuntimeException: INTERNAL: Received headers twice
headers: Metadata(:status=200,content-type=application/grpc,grpc-encoding=identity,grpc-accept-encoding=gzip)
DATA-----------------------------

12123
DATA-----------------------------

12123
trailers: Metadata(grpc-status=0)
	at io.grpc.Status.asRuntimeException(Status.java:543)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:392)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:544)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by thesamet** [comment]
Thanks for the report. Could you create a little project that will help reproducing this issue (both client and server)? Do you have to tell whether the problem is in scalapb's grpc support or in grpc itself?

**Comment by sammerry** [comment]
It seems to be race condition related. Here's the toy repo your asking for. In the server if you change one of the Thread.sleep(10) statements to 20ms it only happens on the first run. Afterward the test completes.

https://github.com/sammerry/grpc_example

**Comment by sammerry** [comment]
This is the important bit. In each future, if the sleep is set to 10ms the duplicate header is thrown. However changing it to a different timeout allows it to run with occasional exceptions.
```scala
 override def sayGoodbye(req: NameRequest, responseObserver: StreamObserver[GoodByeReply]): Unit = {
      val response1 = Promise[GoodByeReply]
      val response2 = Promise[GoodByeReply]

      Future {
        Thread.sleep(10)
        response1.complete(Try(new GoodByeReply(message="good bye 1")))
      }

      Future {
        Thread.sleep(10)
        response2.complete(Try(new GoodByeReply(message="good bye 2")))
      }

      // build list of futures and send them as they resolve
      val futureList = List(response1.future, response2.future)

      val responses = futureList.map { sleeper =>
        val responsePromise = Promise[GoodByeReply]
        sleeper.onComplete {

          case Success(message) => {
            println(s"Future Response Success: $message")
            responseObserver.onNext(message)
            responsePromise.complete(Try(message))
          }

          case Failure(err) =>
            responsePromise.failure(err)
          }

        // convert to a future
        responsePromise.future
      }


      // wait for all futures resolve before completing the stream
      val responseSequence = Future.sequence(responses)
      Await.ready(responseSequence, Duration.Inf)
        .onComplete { x =>
          println("complete")
          Thread.sleep(1000)
          responseObserver.onCompleted()
        }
    }
  }
```

**Comment by thesamet** [comment]
Usage error. See note here for details: https://github.com/grpc/grpc-java/issues/3120#issuecomment-315540704
