### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by GuyIncognito1986** [scalapb/ScalaPB#312]
Hey tried running this under FreeBSD 11/amd64, with protoc 3.3.0 installed from pkg install method, I keep getting the exception below, I tried over riding the protoc compiler with "PB.runProtoc := (args => Process("""protoc""", args)!)" and with
"PB.runProtoc := (args => Process("""/usr/local/bin/protoc""", args)!)", but it does not appear to work....

protoc-jar: protoc version: 330, detected platform: freebsd/amd64
java.lang.RuntimeException: error occurred while compiling protobuf files: Unsupported platform: freebsd/amd64
	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:121)
	at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.scala:144)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.sbtprotoc$ProtocPlugin$$anonfun$$compileProto$1(ProtocPlugin.scala:177)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$7.apply(ProtocPlugin.scala:189)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$7.apply(ProtocPlugin.scala:188)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:195)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:171)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Unsupported platform: freebsd/amd64
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:172)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:194)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:56)
	at sbtprotoc.ProtocPlugin$$anonfun$protobufConfigSettings$13$$anonfun$apply$9.apply(ProtocPlugin.scala:103)
	at sbtprotoc.ProtocPlugin$$anonfun$protobufConfigSettings$13$$anonfun$apply$9.apply(ProtocPlugin.scala:102)
	at protocbridge.ProtocBridge$.runWithGenerators(ProtocBridge.scala:79)
	at protocbridge.ProtocBridge$.run(ProtocBridge.scala:61)
	at sbtprotoc.ProtocPlugin$.executeProtoc(ProtocPlugin.scala:117)
	at sbtprotoc.ProtocPlugin$.sbtprotoc$ProtocPlugin$$compile(ProtocPlugin.scala:144)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.sbtprotoc$ProtocPlugin$$anonfun$$compileProto$1(ProtocPlugin.scala:177)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$7.apply(ProtocPlugin.scala:189)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1$$anonfun$7.apply(ProtocPlugin.scala:188)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:195)
	at sbtprotoc.ProtocPlugin$$anonfun$sourceGeneratorTask$1.apply(ProtocPlugin.scala:171)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by thesamet** [comment]
Can you try `PB.runProtoc in Compile := ...` ?

**Comment by GuyIncognito1986** [comment]
Sure

**Comment by GuyIncognito1986** [comment]
Yep that worked, thank you very much good sir!
