### ISSUE TITLE
OneOf doesn't work

### ISSUE THREAD

**Issue by ArunNachiappan** [scalapb/ScalaPB#315]
I am using scalapb-0.6.1 and facing an issue with OneOf where in None of my specified OneOf objects are parsed with the generated case classes. While everything works fine without OneOf.

**This is my proto  :** 
```
syntax = "proto3";

message Foo {
string cols = 1;
}
message Bar {
string name = 1;
string cols = 2;
}

message Msg {
  string baz = 1;
  oneof some_union {
     Foo foo = 2;
     Bar bar = 3;
  }
}
```

**When I try to extract this JSON String into Class Msg I get only baz as the class member , foo is not parsed** 
```
{
    "baz" : "1",
    "foo" : {
        "cols" : "1"
    }
}

**Comment by thesamet** [comment]
I could not reproduce this problem. I've created a test case based on the proto and json you provided and it does parse the `foo` field.

**Comment by ArunNachiappan** [comment]
Thanks for the update with which I could track the issue. The issue was because I was not using json4s jackson directly. One of works fine with scalapb-json4s. But when I include it my spark project I get this stack trace : 
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/json4s/JsonAST$JLong
	at com.trueaccord.scalapb.json.JsonFormat$.<init>(JsonFormat.scala:214)
	at com.trueaccord.scalapb.json.JsonFormat$.<clinit>(JsonFormat.scala)
	at com.zoho.dpaas.protos.TransformArgument.ProtoTest$.main(ProtoTest.scala:17)
	at com.zoho.dpaas.protos.TransformArgument.ProtoTest.main(ProtoTest.scala)
Caused by: java.lang.ClassNotFoundException: org.json4s.JsonAST$JLong
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

```

This is because spark2.1 uses json4s-3.2.11 where as pb uses 3.5.3. Is there any way I could get rid of this or possibly a work around ?
