### ISSUE TITLE
toByteArray fails for message with only extensions

### ISSUE THREAD

**Issue by skizzybiz** [scalapb/ScalaPB#320]
Calling .toByteArray on a ScalaPB-generated class fails with a `CodedOutputStream$OutOfSpaceException`. This only happens when the message has no fields defined, only extensions, and an extension is populated.

```
> test
[info] ScalapbExtensionSpec:
[info] Foo.toByteArray
[info] - must not blow up *** FAILED ***
[info]   com.google.protobuf.CodedOutputStream$OutOfSpaceException: CodedOutputStream was writing to a flat byte array and ran out of space.: Pos: 1, limit: 0, len: 1
[info]   at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1349)
[info]   at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeTag(CodedOutputStream.java:1174)
[info]   at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeBytes(CodedOutputStream.java:1221)
[info]   at scalapb.UnknownFieldSet$Field$$anonfun$writeTo$5.apply(UnknownFieldSet.scala:46)
[info]   at scalapb.UnknownFieldSet$Field$$anonfun$writeTo$5.apply(UnknownFieldSet.scala:46)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at scalapb.UnknownFieldSet$Field.writeTo(UnknownFieldSet.scala:46)
[info]   ...
[info]   Cause: java.lang.ArrayIndexOutOfBoundsException: 0
[info]   at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeUInt32NoTag(CodedOutputStream.java:1343)
[info]   at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeTag(CodedOutputStream.java:1174)
[info]   at com.google.protobuf.CodedOutputStream$ArrayEncoder.writeBytes(CodedOutputStream.java:1221)
[info]   at scalapb.UnknownFieldSet$Field$$anonfun$writeTo$5.apply(UnknownFieldSet.scala:46)
[info]   at scalapb.UnknownFieldSet$Field$$anonfun$writeTo$5.apply(UnknownFieldSet.scala:46)
[info]   at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[info]   at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[info]   at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[info]   at scalapb.UnknownFieldSet$Field.writeTo(UnknownFieldSet.scala:46)
[info]   ...
[info] Run completed in 279 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed tests:
[error] 	ScalapbExtensionSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 0 s, completed Aug 9, 2017 5:37:42 PM
```

[test-scalapb.zip](https://github.com/scalapb/ScalaPB/files/1213305/test-scalapb.zip)

**Comment by skizzybiz** [comment]
It appears that the generated code assumes that the size will always be 0 when there are no fields defined:

```scala
    final override def serializedSize: Int = 0
```

**Comment by xuwei-k** [comment]
https://github.com/scalapb/ScalaPB/pull/326
