### ISSUE TITLE
JsonFormat.fromJsonString() doesn't parse longs from JSON string values

### ISSUE THREAD

**Issue by skizzybiz** [scalapb/ScalaPB#321]
According to the protobuf 3 spec, when representing an int64:

> JSON value will be a decimal string. Either numbers or strings are accepted.

https://developers.google.com/protocol-buffers/docs/proto3#json

But JsonFormat only accepts numeric JSON values:

```
> test
[info] ScalapbSpec:
[info] JsonFormat.fromJsonString
[info] - must read a large long value *** FAILED ***
[info]   java.lang.NumberFormatException: For input string: "10881926652273085354"
[info]   at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
[info]   at java.lang.Long.parseLong(Long.java:592)
[info]   at java.lang.Long.parseLong(Long.java:631)
[info]   at scala.collection.immutable.StringLike$class.toLong(StringLike.scala:276)
[info]   at scala.collection.immutable.StringOps.toLong(StringOps.scala:29)
[info]   at com.trueaccord.scalapb.json.JsonFormat$.parsePrimitiveByScalaType(JsonFormat.scala:361)
[info]   at com.trueaccord.scalapb.json.Parser.parseSingleValue(JsonFormat.scala:268)
[info]   at com.trueaccord.scalapb.json.Parser.com$trueaccord$scalapb$json$Parser$$parseValue$1(JsonFormat.scala:229)
[info]   at com.trueaccord.scalapb.json.Parser$$anonfun$2$$anonfun$apply$1.apply(JsonFormat.scala:242)
[info]   at com.trueaccord.scalapb.json.Parser$$anonfun$2$$anonfun$apply$1.apply(JsonFormat.scala:241)
[info]   ...
```

[test-scalapb.zip](https://github.com/scalapb/ScalaPB/files/1216692/test-scalapb.zip)

**Comment by mindloaf** [comment]
ScalaPB is accepting a string-valued numeric. The problem is that the string represents an unsigned long, and the code calls `toLong` on it. The code will need to use something like Java's `parseUnsignedLong` where appropriate.
