### ISSUE TITLE
Failure during proto Enum compilation

### ISSUE THREAD

**Issue by optician** [scalapb/ScalaPB#325]
## Version: 
addSbtPlugin("com.thesamet" % "sbt-protoc" % "0.99.12-rc6")
libraryDependencies += "com.trueaccord.scalapb" %% "compilerplugin" % "0.6.2"
sbt 1.0.0 (_it works correctly with sbt 0.13.16_)

## Expected
The schema 
```
syntax = "proto2";

enum MyEnum {
    ELEMENT = 0;
}
```
is compiled.

## Reality
Compilation fails with exception
```
java.lang.NoSuchFieldError: enumOptions
        at com.trueaccord.scalapb.compiler.DescriptorPimps$EnumDescriptorPimp.scalaOptions(DescriptorPimps.scala:380)
        at com.trueaccord.scalapb.compiler.DescriptorPimps$EnumDescriptorPimp.baseTraitExtends(DescriptorPimps.scala:411)
        at com.trueaccord.scalapb.compiler.ProtobufGenerator.printEnum(ProtobufGenerator.scala:23)
        at com.trueaccord.scalapb.compiler.ProtobufGenerator.$anonfun$generateMultipleScalaFilesForFileDescriptor$2(ProtobufGenerator.scala:1293)
        at com.trueaccord.scalapb.compiler.FunctionalPrinter.$anonfun$call$1(FunctionalPrinter.scala:60)
        at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:56)
        at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:64)
        at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:38)
        at com.trueaccord.scalapb.compiler.FunctionalPrinter.call(FunctionalPrinter.scala:60)
        at com.trueaccord.scalapb.compiler.ProtobufGenerator.$anonfun$generateMultipleScalaFilesForFileDescriptor$1(ProtobufGenerator.scala:1293)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at scala.collection.TraversableLike.map(TraversableLike.scala:234)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at com.trueaccord.scalapb.compiler.ProtobufGenerator.generateMultipleScalaFilesForFileDescriptor(ProtobufGenerator.scala:1287)
        at com.trueaccord.scalapb.compiler.ProtobufGenerator$.$anonfun$handleCodeGeneratorRequest$3(ProtobufGenerator.scala:1354)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at com.trueaccord.scalapb.compiler.ProtobufGenerator$.handleCodeGeneratorRequest(ProtobufGenerator.scala:1349)
        at scalapb.ScalaPbCodeGenerator$.run(ScalaPbCodeGenerator.scala:16)
        at protocbridge.frontend.PluginFrontend$.$anonfun$runWithBytes$1(PluginFrontend.scala:56)
        at scala.util.Try$.apply(Try.scala:209)
        at protocbridge.frontend.PluginFrontend$.runWithBytes(PluginFrontend.scala:54)
        at protocbridge.frontend.PluginFrontend$.runWithInputStream(PluginFrontend.scala:67)
        at protocbridge.frontend.WindowsPluginFrontend.$anonfun$prepare$1(WindowsPluginFrontend.scala:23)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
        at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
        at scala.util.Success.$anonfun$map$1(Try.scala:251)
        at scala.util.Success.map(Try.scala:209)
        at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
        at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
        at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by xuwei-k** [comment]
maybe duplicate https://github.com/scalapb/ScalaPB/issues/314

**Comment by optician** [comment]
Imho, important notice that problem appears only for sbt 1.0

**Comment by udaiarora** [comment]
+1
