### ISSUE TITLE
[scalapb-json4s] null field is not treated as default value

### ISSUE THREAD

**Issue by vipo** [scalapb/ScalaPB#336]
According to https://developers.google.com/protocol-buffers/docs/proto3#json "null is accepted and treated as the default value of the corresponding field type". But scalapb throws exception if null (as a message's field) is passed:

```
com.trueaccord.scalapb.json.JsonFormatException: Expected an object, found JNull
	at com.trueaccord.scalapb.json.Parser.fromJsonToPMessage(JsonFormat.scala:246)
	at com.trueaccord.scalapb.json.Parser.parseSingleValue(JsonFormat.scala:267)
```

**Comment by vipo** [comment]
Thank you!
