### ISSUE TITLE
GeneratedCodeSpec fail when Scala 2.12.4 (success Scala 2.12.2)

### ISSUE THREAD

**Issue by xuwei-k** [scalapb/ScalaPB#384]
```
Compiling Scala sources. /var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:164: error: illegal cyclic reference involving class vclsi
object vclsi extends scalapb.GeneratedMessageCompanion[rMjHi.qg.kn.vclsi] with scalapb.JavaProtoSupport[rMjHi.qg.kn.vclsi, whQ7n.vclsi] {
                                                                                                                                 ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:1460: error: illegal cyclic reference involving class vclsi
      object bkz1 extends scalapb.GeneratedMessageCompanion[rMjHi.qg.kn.vclsi.hjazh.u.bkz1] with scalapb.JavaProtoSupport[rMjHi.qg.kn.vclsi.hjazh.u.bkz1, whQ7n.vclsi.hjazh.u.bkz1] {
                                                                                                                                                                              ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:167: error: value newBuilder is not a member of object whQ7n.vclsi
    val javaPbOut = whQ7n.vclsi.newBuilder
                                ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:184: error: illegal cyclic reference involving class vclsi
    ru = if (javaPbSource.hasRu) Some(rMjHi.qg.kn.vclsi.hjazh.u.bkz1.fromJavaProto(javaPbSource.getRu)) else None,
                          ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:516: error: illegal cyclic reference involving class vclsi
  object n extends scalapb.GeneratedMessageCompanion[rMjHi.qg.kn.vclsi.n] with scalapb.JavaProtoSupport[rMjHi.qg.kn.vclsi.n, whQ7n.vclsi.n] {
                                                                                                                                         ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:519: error: illegal cyclic reference involving class vclsi
      val javaPbOut = whQ7n.vclsi.n.newBuilder
                                    ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:788: error: illegal cyclic reference involving class vclsi
      val javaPbOut = whQ7n.vclsi.hjazh.newBuilder
                                        ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:1072: error: illegal cyclic reference involving class vclsi
    object tnmqW extends scalapb.GeneratedMessageCompanion[rMjHi.qg.kn.vclsi.hjazh.tnmqW] with scalapb.JavaProtoSupport[rMjHi.qg.kn.vclsi.hjazh.tnmqW, whQ7n.vclsi.hjazh.tnmqW] {
                                                                                                                                                                         ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:1075: error: illegal cyclic reference involving class vclsi
        val javaPbOut = whQ7n.vclsi.hjazh.tnmqW.newBuilder
                                                ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:1210: error: illegal cyclic reference involving class vclsi
        val javaPbOut = whQ7n.vclsi.hjazh.u.newBuilder
                                            ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/rMjHi/qg/kn/vclsi.scala:1463: error: illegal cyclic reference involving class vclsi
          val javaPbOut = whQ7n.vclsi.hjazh.u.bkz1.newBuilder
                                                   ^
/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081/nzs/yred/xlzx/u.scala:559: error: illegal cyclic reference involving class vclsi
        javaPbOut.setVq9Re(rMjHi.qg.kn.vclsi.toJavaProto(scalaPbSource.vq9Re))
                  ^
[DONE]
scala.ScalaReflectionException: object rMjHi.qg.kn.vclsi$hjazh$u not found.
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:161)
	at scala.reflect.internal.Mirrors$RootsBase.staticModule(Mirrors.scala:22)
	at SchemaGenerators$CompiledSchema.scalaObject(SchemaGenerators.scala:195)
	at GeneratedCodeSpec.$anonfun$new$11(GeneratedCodeSpec.scala:42)
	at GeneratedCodeSpec.$anonfun$new$11$adapted(GeneratedCodeSpec.scala:34)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.liftedTree9$1(GeneratorDrivenPropertyChecks.scala:931)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.$anonfun$forAll$7(GeneratorDrivenPropertyChecks.scala:930)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:712)
	at org.scalacheck.Prop$.secure(Prop.scala:456)
	at org.scalacheck.Prop$.result$1(Prop.scala:712)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
	at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
	at org.scalacheck.PropFromFun.apply(Prop.scala:22)
	at org.scalacheck.Test$.workerFun$1(Test.scala:294)
	at org.scalacheck.Test$.$anonfun$check$1(Test.scala:323)
	at org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:323)
	at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
	at org.scalacheck.Test$.check(Test.scala:323)
	at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:89)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:944)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:920)
	at GeneratedCodeSpec.forAll(GeneratedCodeSpec.scala:17)
	at GeneratedCodeSpec.$anonfun$new$10(GeneratedCodeSpec.scala:34)
	at GeneratedCodeSpec.$anonfun$new$10$adapted(GeneratedCodeSpec.scala:33)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.liftedTree9$1(GeneratorDrivenPropertyChecks.scala:931)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.$anonfun$forAll$7(GeneratorDrivenPropertyChecks.scala:930)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$2(Prop.scala:712)
	at org.scalacheck.Prop$.secure(Prop.scala:456)
	at org.scalacheck.Prop$.result$1(Prop.scala:712)
	at org.scalacheck.Prop$.$anonfun$forAllShrink$1(Prop.scala:749)
	at org.scalacheck.Prop$.$anonfun$apply$1(Prop.scala:292)
	at org.scalacheck.PropFromFun.apply(Prop.scala:22)
	at org.scalacheck.Test$.workerFun$1(Test.scala:294)
	at org.scalacheck.Test$.$anonfun$check$1(Test.scala:323)
	at org.scalacheck.Test$.$anonfun$check$1$adapted(Test.scala:323)
	at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
	at org.scalacheck.Test$.check(Test.scala:323)
	at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:89)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll(GeneratorDrivenPropertyChecks.scala:944)
	at org.scalatest.prop.GeneratorDrivenPropertyChecks.forAll$(GeneratorDrivenPropertyChecks.scala:920)
	at GeneratedCodeSpec.forAll(GeneratedCodeSpec.scala:17)
	at GeneratedCodeSpec.$anonfun$new$9(GeneratedCodeSpec.scala:32)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.PropSpecLike$$anon$1.apply(PropSpecLike.scala:186)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.PropSpec.withFixture(PropSpec.scala:874)
	at org.scalatest.PropSpecLike.invokeWithFixture$1(PropSpecLike.scala:184)
	at org.scalatest.PropSpecLike.$anonfun$runTest$1(PropSpecLike.scala:196)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.PropSpecLike.runTest(PropSpecLike.scala:196)
	at org.scalatest.PropSpecLike.runTest$(PropSpecLike.scala:178)
	at org.scalatest.PropSpec.runTest(PropSpec.scala:874)
	at org.scalatest.PropSpecLike.$anonfun$runTests$1(PropSpecLike.scala:229)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.PropSpecLike.runTests(PropSpecLike.scala:229)
	at org.scalatest.PropSpecLike.runTests$(PropSpecLike.scala:228)
	at org.scalatest.PropSpec.runTests(PropSpec.scala:874)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.PropSpec.org$scalatest$PropSpecLike$$super$run(PropSpec.scala:874)
	at org.scalatest.PropSpecLike.$anonfun$run$1(PropSpecLike.scala:233)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.PropSpecLike.run(PropSpecLike.scala:233)
	at org.scalatest.PropSpecLike.run$(PropSpecLike.scala:232)
	at org.scalatest.PropSpec.run(PropSpec.scala:874)
	at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:314)
	at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:507)
	at sbt.TestRunner.runTest$1(TestFramework.scala:76)
	at sbt.TestRunner.run(TestFramework.scala:85)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1$$anonfun$apply$8.apply(TestFramework.scala:202)
	at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:185)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFramework$$anon$2$$anonfun$$init$$1.apply(TestFramework.scala:202)
	at sbt.TestFunction.apply(TestFramework.scala:207)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.Tests$$anonfun$9.apply(Tests.scala:216)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
()
Message: u
[info] GeneratedCodeSpec:
[info] - min and max id are consecutive over files
[info] - Java and Scala protos are equivalent *** FAILED ***
[info]   GeneratorDrivenPropertyCheckFailedException was thrown during property evaluation.
[info]     Message: RuntimeException was thrown during property evaluation.
[info]     Message: object rMjHi.qg.kn.vclsi$hjazh$u not found.
[info]     Occurred when passed generated values (
[info]       arg0 = (MessageNode(5,u,List(MessageNode(6,bkz1,List(),List(EnumNode(5,fe6b,List((oxe,0), (d,18), (i,3), (c,15)),Some(6),1), EnumNode(6,avwli,List((nh6it,0), (eennU,12), (o6rr,2), (a6ij,22)),Some(6),1)),List(FieldNode(alyt,Primitive(uint64),FieldOptions(optional,false),NotInOneof,1), FieldNode(nx,Primitive(uint32),FieldOptions(optional,false),NotInOneof,2)),Some(5),1)),List(EnumNode(7,wi,List((y,0)),Some(5),1), EnumNode(8,wys,List((mmf,0), (c,13), (kc,12)),Some(5),1), EnumNode(9,zpmzm,List((oy,0), (w5sam,12), (rxk6,11), (kwy0x,6)),Some(5),1)),List(),Some(3),1),MessageValue(ArrayBuffer()))
[info]     )
[info]     Location: (GeneratedCodeSpec.scala:34)
[info]     Occurred when passed generated values (
[info]       arg0 = CompiledSchema(dq.proto:
[info]   
[info]   // File id 0. messages: Some(0)-Some(0). Enums: Some(0)-Some(0)
[info]   syntax = "proto3";
[info]   package m9ni;
[info]   option java_package = "inwb.g.fe3m";
[info]   option java_multiple_files = true;
[info]   import "scalapb/scalapb.proto";
[info]   option (scalapb.options) = {
[info]     package_name: "ia"
[info]     flat_package: false
[info]   };
[info]   message lvofh {  // message 0
[info]     enum lxzd {  // enum 0
[info]       w = 0;
[info]       rd = 1;
[info]       epnes = 5;
[info]     }
[info]     repeated m9ni.lvofh.lxzd m = 11;  // EnumReference(0)
[info]     repeated int64 zd = 10;  // Primitive(int64)
[info]     sint32 rxjio = 13;  // Primitive(sint32)
[info]   }
[info]   
[info]   service hmt5 {
[info]     rpc pbtq (lvofh) returns (stream lvofh) {};
[info]     rpc wzhay (lvofh) returns (lvofh) {};
[info]     rpc q2 (stream lvofh) returns (stream lvofh) {};
[info]   }
[info]   service odj {
[info]     rpc woes (stream lvofh) returns (stream lvofh) {};
[info]     rpc wh (lvofh) returns (lvofh) {};
[info]     rpc kl (lvofh) returns (stream lvofh) {};
[info]   }
[info]   service hu {
[info]   }
[info]   pefhb.proto:
[info]   
[info]   // File id 1. messages: Some(1)-Some(6). Enums: Some(1)-Some(17)
[info]   syntax = "proto3";
[info]   package bnovc;
[info]   option java_package = "whQ7n";
[info]   option java_multiple_files = true;
[info]   import "scalapb/scalapb.proto";
[info]   option (scalapb.options) = {
[info]     package_name: "rMjHi.qg.kn"
[info]     flat_package: true
[info]   };
[info]   import "dq.proto";
[info]   enum f {  // enum 16
[info]     n = 0;
[info]     py = 19;
[info]     c550 = 20;
[info]     wzm = 10;
[info]   }
[info]   enum rYpYy {  // enum 17
[info]     i = 0;
[info]     jV = 13;
[info]     ctt = 10;
[info]     dS = 12;
[info]   }
[info]   message vclsi {  // message 1
[info]     enum msJj {  // enum 13
[info]       jDqei = 0;
[info]       xdq = 9;
[info]       lqde = 11;
[info]     }
[info]     enum klip9 {  // enum 14
[info]       uYy4o = 0;
[info]       fhpw = 1;
[info]       xo = 3;
[info]     }
[info]     enum bo {  // enum 15
[info]       ghnK = 0;
[info]     }
[info]     message n {  // message 2
[info]       enum m2 {  // enum 1
[info]         cyvm = 0;
[info]       }
[info]       enum lHe2 {  // enum 2
[info]         npxox = 0;
[info]       }
[info]       oneof aH {
[info]         uint64 tw = 7;  // Primitive(uint64)
[info]       }  // oneof aH
[info]       repeated bnovc.vclsi.n.m2 d5e = 14 [packed = true];  // EnumReference(1)
[info]       m9ni.lvofh.lxzd j9bd = 12;  // EnumReference(0)
[info]       m9ni.lvofh j = 2;  // MessageReference(0)
[info]       fixed64 zabff = 20;  // Primitive(fixed64)
[info]     }
[info]   
[info]     message hjazh {  // message 3
[info]       enum p {  // enum 10
[info]         uf = 0;
[info]         gidnO = 10;
[info]         dvxb9 = 12;
[info]         o = 13;
[info]       }
[info]       enum kjf {  // enum 11
[info]         r3hg = 0;
[info]         kaaw = 4;
[info]         f = 14;
[info]       }
[info]       enum rb {  // enum 12
[info]         lrz = 0;
[info]         fK = 5;
[info]       }
[info]       message tnmqW {  // message 4
[info]         enum k {  // enum 3
[info]           nlba = 0;
[info]           r = 9;
[info]           mbc = 16;
[info]         }
[info]         enum f {  // enum 4
[info]           u = 0;
[info]         }
[info]       }
[info]   
[info]       message u {  // message 5
[info]         enum wi {  // enum 7
[info]           y = 0;
[info]         }
[info]         enum wys {  // enum 8
[info]           mmf = 0;
[info]           c = 13;
[info]           kc = 12;
[info]         }
[info]         enum zpmzm {  // enum 9
[info]           oy = 0;
[info]           w5sam = 12;
[info]           rxk6 = 11;
[info]           kwy0x = 6;
[info]         }
[info]         message bkz1 {  // message 6
[info]           enum fe6b {  // enum 5
[info]             oxe = 0;
[info]             d = 18;
[info]             i = 3;
[info]             c = 15;
[info]           }
[info]           enum avwli {  // enum 6
[info]             nh6it = 0;
[info]             eennU = 12;
[info]             o6rr = 2;
[info]             a6ij = 22;
[info]           }
[info]           uint64 alyt = 1;  // Primitive(uint64)
[info]           uint32 nx = 2;  // Primitive(uint32)
[info]         }
[info]   
[info]       }
[info]   
[info]       bytes eo = 8;  // Primitive(bytes)
[info]       oneof ppu {
[info]         fixed64 rrt = 14;  // Primitive(fixed64)
[info]         float rbj6 = 3;  // Primitive(float)
[info]       }  // oneof ppu
[info]       oneof uzl {
[info]         bool un = 9;  // Primitive(bool)
[info]       }  // oneof uzl
[info]     }
[info]   
[info]     repeated bool qcai = 13;  // Primitive(bool)
[info]     map<fixed32, sint32> hb = 12;  // MapType(Primitive(fixed32),Primitive(sint32))
[info]     bnovc.vclsi.hjazh.u.bkz1 ru = 2;  // MessageReference(6)
[info]     int32 tpY = 23;  // Primitive(int32)
[info]     bnovc.vclsi.hjazh.u ok6pp = 3;  // MessageReference(5)
[info]   }
[info]   
[info]   c.proto:
[info]   
[info]   // File id 2. messages: None-None. Enums: Some(18)-Some(18)
[info]   syntax = "proto3";
[info]   option java_package = "aam.hndef.eHty.fcgt";
[info]   option java_multiple_files = true;
[info]   import "scalapb/scalapb.proto";
[info]   option (scalapb.options) = {
[info]     package_name: "n9.wqt"
[info]     flat_package: true
[info]   };
[info]   enum de4bv {  // enum 18
[info]     noo5 = 0;
[info]     pn = 28;
[info]     gjdjs = 30;
[info]     drh = 20;
[info]   }
[info]   service og {
[info]   }
[info]   l.proto:
[info]   
[info]   // File id 3. messages: Some(7)-Some(14). Enums: Some(19)-Some(37)
[info]   syntax = "proto2";
[info]   option java_package = "h.tku.ul.zm";
[info]   import "scalapb/scalapb.proto";
[info]   option (scalapb.options) = {
[info]     package_name: "nzs.yred.xlzx"
[info]     flat_package: true
[info]   };
[info]   import "dq.proto";
[info]   import "pefhb.proto";
[info]   enum zUcb {  // enum 35
[info]     g073l = 0;
[info]   }
[info]   enum v4 {  // enum 36
[info]     rsWbw = 0;
[info]     i5 = 9;
[info]     p0 = 1;
[info]     j7nhy = 27;
[info]   }
[info]   enum hhz {  // enum 37
[info]     f = 0;
[info]     ene = 2;
[info]     umGV = 11;
[info]     a = 1;
[info]   }
[info]   message u {  // message 7
[info]     enum r {  // enum 34
[info]       y = 0;
[info]       f0 = 10;
[info]       xk6 = 17;
[info]       jkt = 24;
[info]     }
[info]     message ain {  // message 8
[info]       enum kiv2 {  // enum 27
[info]         mlr = 2;
[info]         utyw = 1;
[info]       }
[info]       enum l8k {  // enum 28
[info]         m = 0;
[info]         wa = 3;
[info]         eax = 1;
[info]       }
[info]       enum yqhd {  // enum 29
[info]         mYhE = 3;
[info]         itwd = 1;
[info]         qf = 10;
[info]         ozy = 21;
[info]         b1k = 11;
[info]       }
[info]       message ai3ku {  // message 9
[info]         enum q {  // enum 22
[info]           vDzf = 0;
[info]           yql = 11;
[info]           vbgVT = 2;
[info]         }
[info]         enum blj {  // enum 23
[info]           vDj3x = 0;
[info]           yLgyb = 9;
[info]           wv = 8;
[info]         }
[info]         enum wcn {  // enum 24
[info]           s3x = 2;
[info]           xbeE = 1;
[info]         }
[info]         message vjZF {  // message 10
[info]           enum cknby {  // enum 19
[info]             ra = 9;
[info]             cfbp = 1;
[info]           }
[info]           enum e {  // enum 20
[info]             ja = 3;
[info]             snyq = 11;
[info]           }
[info]           enum lff1 {  // enum 21
[info]             kvl = 2;
[info]             t2 = 1;
[info]             b1 = 8;
[info]           }
[info]           repeated bnovc.vclsi.hjazh.u.wys yD = 10;  // EnumReference(8)
[info]           required bytes plz = 26;  // Primitive(bytes)
[info]           required int64 ba = 16;  // Primitive(int64)
[info]           optional m9ni.lvofh.lxzd qak = 8;  // EnumReference(0)
[info]         }
[info]   
[info]         repeated sint32 z = 13;  // Primitive(sint32)
[info]         repeated m9ni.lvofh afkxg = 22;  // MessageReference(0)
[info]         required bnovc.vclsi vq9re = 5;  // MessageReference(1)
[info]       }
[info]   
[info]       message yec {  // message 11
[info]         enum t {  // enum 25
[info]           qoq = 0;
[info]         }
[info]         enum qn {  // enum 26
[info]           y5 = 21;
[info]           edcc = 11;
[info]           os5Un = 12;
[info]           qz7as = 1;
[info]         }
[info]         map<fixed64, sfixed32> fo = 2;  // MapType(Primitive(fixed64),Primitive(sfixed32))
[info]         oneof z {
[info]           bool jp8o2 = 1;  // Primitive(bool)
[info]         }  // oneof z
[info]       }
[info]   
[info]     }
[info]   
[info]     message fs {  // message 12
[info]       message xa1a {  // message 13
[info]         enum vwoh {  // enum 30
[info]           bhet = 5;
[info]           xddm7 = 7;
[info]           s0wu7 = 6;
[info]         }
[info]         enum hLsn {  // enum 31
[info]           td4bm = 0;
[info]           jrdgz = 4;
[info]         }
[info]         required sint32 knTj = 1;  // Primitive(sint32)
[info]       }
[info]   
[info]     }
[info]   
[info]     message dr {  // message 14
[info]       enum pcde3 {  // enum 32
[info]         tj = 0;
[info]         v2wGl = 18;
[info]         xdhs = 4;
[info]       }
[info]       enum nf {  // enum 33
[info]         qrk = 0;
[info]       }
[info]     }
[info]   
[info]     required sint32 mc = 3;  // Primitive(sint32)
[info]     repeated fixed32 oKdl = 1;  // Primitive(fixed32)
[info]     map<int64, string> x = 13;  // MapType(Primitive(int64),Primitive(string))
[info]   }
[info]   
[info]   service xp {
[info]     rpc dPv (u) returns (u) {};
[info]     rpc o4rhh (stream u) returns (stream u) {};
[info]     rpc k (stream u) returns (u) {};
[info]   },/var/folders/hw/vqly1hs14p77yl70qbqzsxk00000gq/T/set_1672899296653351081)
[info]     )
[info] ScalaTest
[info] Run completed in 7 seconds, 554 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error] 	GeneratedCodeSpec
```

**Comment by thesamet** [comment]
Not sure why Scalac `-Ybreak-cycles` is needed in 2.12.4. SBT doesn't seem to have an issue compiling the same files without this flag. Oh well.
