### ISSUE TITLE
Getting runtimeException  java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by qux42** [scalapb/ScalaPB#426]
Using the newest scalapb and grpc version i get following runtime-exception:

```java.lang.RuntimeException: Exception in Application start method
java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: com.google.protobuf.Descriptors$Descriptor.getOneofs()Ljava/util/List;
	at com.google.protobuf.GeneratedMessageV3$FieldAccessorTable.<init>(GeneratedMessageV3.java:1727)
	at com.google.protobuf.EmptyProto.<clinit>(EmptyProto.java:51)
	at com.google.protobuf.empty.EmptyProto$.javaDescriptor$lzycompute(EmptyProto.scala:25)
	at com.google.protobuf.empty.EmptyProto$.javaDescriptor(EmptyProto.scala:24)
```

I have the following dependency-tree:

```[info] default:motioneditor_2.12:1.0 [S]
[info]   +-ch.qos.logback:logback-classic:1.2.3
[info]   | +-ch.qos.logback:logback-core:1.2.3
[info]   | +-org.slf4j:slf4j-api:1.7.25
[info]   | 
[info]   +-com.thesamet.scalapb:scalapb-runtime-grpc_2.12:0.7.1 [S]
[info]   | +-com.thesamet.scalapb:scalapb-runtime_2.12:0.7.1 [S]
[info]   | | +-com.google.protobuf:protobuf-java:3.5.0 (evicted by: 3.5.1)
[info]   | | +-com.google.protobuf:protobuf-java:3.5.1
[info]   | | +-com.lihaoyi:fastparse_2.12:1.0.0 [S]
[info]   | | | +-com.lihaoyi:fastparse-utils_2.12:1.0.0 [S]
[info]   | | | | +-com.lihaoyi:sourcecode_2.12:0.1.4 [S]
[info]   | | | | 
[info]   | | | +-com.lihaoyi:sourcecode_2.12:0.1.4 [S]
[info]   | | | 
[info]   | | +-com.thesamet.scalapb:lenses_2.12:0.7.0-test2 [S]
[info]   | | 
[info]   | +-io.grpc:grpc-protobuf:1.10.0
[info]   | | +-com.google.api.grpc:proto-google-common-protos:1.0.0
[info]   | | +-com.google.guava:guava:19.0
[info]   | | +-com.google.protobuf:protobuf-java-util:3.5.1
[info]   | | | +-com.google.code.gson:gson:2.7
[info]   | | | +-com.google.guava:guava:19.0
[info]   | | | +-com.google.protobuf:protobuf-java:3.5.1
[info]   | | | 
[info]   | | +-com.google.protobuf:protobuf-java:3.5.1
[info]   | | +-io.grpc:grpc-core:1.10.0
[info]   | | | +-com.google.code.findbugs:jsr305:3.0.0
[info]   | | | +-com.google.code.gson:gson:2.7
[info]   | | | +-com.google.errorprone:error_prone_annotations:2.1.2
[info]   | | | +-com.google.guava:guava:19.0
[info]   | | | +-io.grpc:grpc-context:1.10.0
[info]   | | | +-io.opencensus:opencensus-api:0.11.0
[info]   | | | | +-com.google.guava:guava:19.0
[info]   | | | | 
[info]   | | | +-io.opencensus:opencensus-contrib-grpc-metrics:0.11.0
[info]   | | |   +-io.opencensus:opencensus-api:0.11.0
[info]   | | |     +-com.google.guava:guava:19.0
[info]   | | |     
[info]   | | +-io.grpc:grpc-protobuf-lite:1.10.0
[info]   | |   +-com.google.guava:guava:19.0
[info]   | |   +-io.grpc:grpc-core:1.10.0
[info]   | |     +-com.google.code.findbugs:jsr305:3.0.0
[info]   | |     +-com.google.code.gson:gson:2.7
[info]   | |     +-com.google.errorprone:error_prone_annotations:2.1.2
[info]   | |     +-com.google.guava:guava:19.0
[info]   | |     +-io.grpc:grpc-context:1.10.0
[info]   | |     +-io.opencensus:opencensus-api:0.11.0
[info]   | |     | +-com.google.guava:guava:19.0
[info]   | |     | 
[info]   | |     +-io.opencensus:opencensus-contrib-grpc-metrics:0.11.0
[info]   | |       +-io.opencensus:opencensus-api:0.11.0
[info]   | |         +-com.google.guava:guava:19.0
[info]   | |         
[info]   | +-io.grpc:grpc-stub:1.10.0
[info]   |   +-io.grpc:grpc-core:1.10.0
[info]   |     +-com.google.code.findbugs:jsr305:3.0.0
[info]   |     +-com.google.code.gson:gson:2.7
[info]   |     +-com.google.errorprone:error_prone_annotations:2.1.2
[info]   |     +-com.google.guava:guava:19.0
[info]   |     +-io.grpc:grpc-context:1.10.0
[info]   |     +-io.opencensus:opencensus-api:0.11.0
[info]   |     | +-com.google.guava:guava:19.0
[info]   |     | 
[info]   |     +-io.opencensus:opencensus-contrib-grpc-metrics:0.11.0
[info]   |       +-io.opencensus:opencensus-api:0.11.0
[info]   |         +-com.google.guava:guava:19.0
[info]   |         
[info]   +-com.thesamet.scalapb:scalapb-runtime_2.12:0.7.1 [S]
[info]   | +-com.google.protobuf:protobuf-java:3.5.0 (evicted by: 3.5.1)
[info]   | +-com.google.protobuf:protobuf-java:3.5.1
[info]   | +-com.lihaoyi:fastparse_2.12:1.0.0 [S]
[info]   | | +-com.lihaoyi:fastparse-utils_2.12:1.0.0 [S]
[info]   | | | +-com.lihaoyi:sourcecode_2.12:0.1.4 [S]
[info]   | | | 
[info]   | | +-com.lihaoyi:sourcecode_2.12:0.1.4 [S]
[info]   | | 
[info]   | +-com.thesamet.scalapb:lenses_2.12:0.7.0-test2 [S]
[info]   | 
[info]   +-com.typesafe.akka:akka-actor_2.12:2.5.3 [S]
[info]   | +-com.typesafe:config:1.3.1
[info]   | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | 
[info]   +-com.typesafe.akka:akka-agent_2.12:2.5.3 [S]
[info]   | +-com.typesafe.akka:akka-actor_2.12:2.5.3 [S]
[info]   | | +-com.typesafe:config:1.3.1
[info]   | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | | 
[info]   | +-org.scala-stm:scala-stm_2.12:0.8 [S]
[info]   | 
[info]   +-com.typesafe.akka:akka-slf4j_2.12:2.5.3 [S]
[info]   | +-com.typesafe.akka:akka-actor_2.12:2.5.3 [S]
[info]   | | +-com.typesafe:config:1.3.1
[info]   | | +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   | | 
[info]   | +-org.slf4j:slf4j-api:1.7.23 (evicted by: 1.7.25)
[info]   | +-org.slf4j:slf4j-api:1.7.25
[info]   | 
[info]   +-com.typesafe.akka:akka-typed_2.12:2.5.3 [S]
[info]   | +-com.typesafe.akka:akka-testkit_2.12:2.5.3 [S]
[info]   |   +-com.typesafe.akka:akka-actor_2.12:2.5.3 [S]
[info]   |     +-com.typesafe:config:1.3.1
[info]   |     +-org.scala-lang.modules:scala-java8-compat_2.12:0.8.0 [S]
[info]   |     
[info]   +-com.typesafe.scala-logging:scala-logging_2.12:3.8.0 [S]
[info]   | +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | +-org.slf4j:slf4j-api:1.7.25
[info]   | 
[info]   +-io.circe:circe-core_2.12:0.9.3 [S]
[info]   | +-io.circe:circe-numbers_2.12:0.9.3 [S]
[info]   | +-org.typelevel:cats-core_2.12:1.0.1 [S]
[info]   |   +-org.typelevel:cats-kernel_2.12:1.0.1 [S]
[info]   |   +-org.typelevel:cats-macros_2.12:1.0.1 [S]
[info]   |   | +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   |   |   +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   |   |   
[info]   |   +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   |     +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   |     
[info]   +-io.circe:circe-generic_2.12:0.9.3 [S]
[info]   | +-com.chuusai:shapeless_2.12:2.3.3 [S]
[info]   | | +-org.typelevel:macro-compat_2.12:1.1.1 [S]
[info]   | | 
[info]   | +-io.circe:circe-core_2.12:0.9.3 [S]
[info]   | | +-io.circe:circe-numbers_2.12:0.9.3 [S]
[info]   | | +-org.typelevel:cats-core_2.12:1.0.1 [S]
[info]   | |   +-org.typelevel:cats-kernel_2.12:1.0.1 [S]
[info]   | |   +-org.typelevel:cats-macros_2.12:1.0.1 [S]
[info]   | |   | +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   | |   |   +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | |   |   
[info]   | |   +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   | |     +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | |     
[info]   | +-org.typelevel:macro-compat_2.12:1.1.1 [S]
[info]   | 
[info]   +-io.circe:circe-parser_2.12:0.9.3 [S]
[info]   | +-io.circe:circe-core_2.12:0.9.3 [S]
[info]   | | +-io.circe:circe-numbers_2.12:0.9.3 [S]
[info]   | | +-org.typelevel:cats-core_2.12:1.0.1 [S]
[info]   | |   +-org.typelevel:cats-kernel_2.12:1.0.1 [S]
[info]   | |   +-org.typelevel:cats-macros_2.12:1.0.1 [S]
[info]   | |   | +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   | |   |   +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | |   |   
[info]   | |   +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   | |     +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | |     
[info]   | +-io.circe:circe-jawn_2.12:0.9.3 [S]
[info]   |   +-io.circe:circe-core_2.12:0.9.3 [S]
[info]   |   | +-io.circe:circe-numbers_2.12:0.9.3 [S]
[info]   |   | +-org.typelevel:cats-core_2.12:1.0.1 [S]
[info]   |   |   +-org.typelevel:cats-kernel_2.12:1.0.1 [S]
[info]   |   |   +-org.typelevel:cats-macros_2.12:1.0.1 [S]
[info]   |   |   | +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   |   |   |   +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   |   |   |   
[info]   |   |   +-org.typelevel:machinist_2.12:0.6.2 [S]
[info]   |   |     +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   |   |     
[info]   |   +-org.spire-math:jawn-parser_2.12:0.11.1 [S]
[info]   |   
[info]   +-io.grpc:grpc-netty:1.10.0
[info]   | +-io.grpc:grpc-core:1.10.0
[info]   | | +-com.google.code.findbugs:jsr305:3.0.0
[info]   | | +-com.google.code.gson:gson:2.7
[info]   | | +-com.google.errorprone:error_prone_annotations:2.1.2
[info]   | | +-com.google.guava:guava:19.0
[info]   | | +-io.grpc:grpc-context:1.10.0
[info]   | | +-io.opencensus:opencensus-api:0.11.0
[info]   | | | +-com.google.guava:guava:19.0
[info]   | | | 
[info]   | | +-io.opencensus:opencensus-contrib-grpc-metrics:0.11.0
[info]   | |   +-io.opencensus:opencensus-api:0.11.0
[info]   | |     +-com.google.guava:guava:19.0
[info]   | |     
[info]   | +-io.netty:netty-codec-http2:4.1.17.Final
[info]   | | +-io.netty:netty-codec-http:4.1.17.Final
[info]   | | | +-io.netty:netty-codec:4.1.17.Final
[info]   | | |   +-io.netty:netty-transport:4.1.17.Final
[info]   | | |     +-io.netty:netty-buffer:4.1.17.Final
[info]   | | |     | +-io.netty:netty-common:4.1.17.Final
[info]   | | |     | 
[info]   | | |     +-io.netty:netty-resolver:4.1.17.Final
[info]   | | |       +-io.netty:netty-common:4.1.17.Final
[info]   | | |       
[info]   | | +-io.netty:netty-handler:4.1.17.Final
[info]   | |   +-io.netty:netty-buffer:4.1.17.Final
[info]   | |   | +-io.netty:netty-common:4.1.17.Final
[info]   | |   | 
[info]   | |   +-io.netty:netty-codec:4.1.17.Final
[info]   | |   | +-io.netty:netty-transport:4.1.17.Final
[info]   | |   |   +-io.netty:netty-buffer:4.1.17.Final
[info]   | |   |   | +-io.netty:netty-common:4.1.17.Final
[info]   | |   |   | 
[info]   | |   |   +-io.netty:netty-resolver:4.1.17.Final
[info]   | |   |     +-io.netty:netty-common:4.1.17.Final
[info]   | |   |     
[info]   | |   +-io.netty:netty-transport:4.1.17.Final
[info]   | |     +-io.netty:netty-buffer:4.1.17.Final
[info]   | |     | +-io.netty:netty-common:4.1.17.Final
[info]   | |     | 
[info]   | |     +-io.netty:netty-resolver:4.1.17.Final
[info]   | |       +-io.netty:netty-common:4.1.17.Final
[info]   | |       
[info]   | +-io.netty:netty-handler-proxy:4.1.17.Final
[info]   |   +-io.netty:netty-codec-http:4.1.17.Final
[info]   |   | +-io.netty:netty-codec:4.1.17.Final
[info]   |   |   +-io.netty:netty-transport:4.1.17.Final
[info]   |   |     +-io.netty:netty-buffer:4.1.17.Final
[info]   |   |     | +-io.netty:netty-common:4.1.17.Final
[info]   |   |     | 
[info]   |   |     +-io.netty:netty-resolver:4.1.17.Final
[info]   |   |       +-io.netty:netty-common:4.1.17.Final
[info]   |   |       
[info]   |   +-io.netty:netty-codec-socks:4.1.17.Final
[info]   |   | +-io.netty:netty-codec:4.1.17.Final
[info]   |   |   +-io.netty:netty-transport:4.1.17.Final
[info]   |   |     +-io.netty:netty-buffer:4.1.17.Final
[info]   |   |     | +-io.netty:netty-common:4.1.17.Final
[info]   |   |     | 
[info]   |   |     +-io.netty:netty-resolver:4.1.17.Final
[info]   |   |       +-io.netty:netty-common:4.1.17.Final
[info]   |   |       
[info]   |   +-io.netty:netty-transport:4.1.17.Final
[info]   |     +-io.netty:netty-buffer:4.1.17.Final
[info]   |     | +-io.netty:netty-common:4.1.17.Final
[info]   |     | 
[info]   |     +-io.netty:netty-resolver:4.1.17.Final
[info]   |       +-io.netty:netty-common:4.1.17.Final
[info]   |       
[info]   +-org.scalafx:scalafx_2.12:8.0.144-R12 [S]
[info]   | +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | 
[info]   +-org.scalamock:scalamock-scalatest-support_2.12:3.6.0 [S]
[info]   | +-org.scalamock:scalamock-core_2.12:3.6.0 [S]
[info]   | | +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   | | 
[info]   | +-org.scalatest:scalatest_2.12:3.0.1 [S]
[info]   |   +-org.scala-lang.modules:scala-parser-combinators_2.12:1.0.4 [S]
[info]   |   +-org.scala-lang.modules:scala-xml_2.12:1.0.5 [S]
[info]   |   +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   |   +-org.scalactic:scalactic_2.12:3.0.1 [S]
[info]   |     +-org.scala-lang:scala-reflect:2.12.5 [S]
[info]   |     
[info]   +-org.scalaz:scalaz-core_2.12:7.2.21 [S]
[info]   
```

with an old version of scalapb it was working.

**Comment by thesamet** [comment]
Can you create a minimal project that demonstrates this problem?

**Comment by thesamet** [comment]
I haven't received any response on how to reproduce this issue for a while so I am closing this ticket. Feel free to reach out if this problem is still relevant.
