### ISSUE TITLE
Repeated Wrapper Type

### ISSUE THREAD

**Issue by vipo** [scalapb/ScalaPB#465]
Currently
`repeated google.protobuf.StringValue optional_strings = 1;`
is compiled into
`optionalStrings: Seq[String] = Seq.empty`
which, I believe, is incorrect and should be
`optionalStrings: Seq[Option[String]] = Seq.empty`.

Is this behavior intended or maybe is it a bug?

**Comment by thesamet** [comment]
This behavior seems confusing but is actually consistent with how ScalaPB does type transformations. `StringValue` is type-mapped to a `String`. So as an optional message field it will become `Option[String]`, but as a repeated message it will become `Seq[String]`.

To achieve the effect that you want, you'd actually have to wrap `StringValue` again:

message OptionalString {
  StringValue value = 1;
}

You can create a type mapper for OptionalString to `Option[String]` so when it appears in a repeated field you will get the type that you want.

**Comment by vipo** [comment]
Thank you for your explanation, it sounds reasonable, indeed. But please comment on our initial problem then (which is related to json4s integration).
Our idl is:
`repeated google.protobuf.StringValue optional_strings = 1;`
json sub-message is:
`[null, "bblah"]`
error we get is:
```
scalapb.json4s.JsonFormatException: Unexpected value for StringValue
	at scalapb.json4s.JsonFormat$.$anonfun$primitiveWrapperParser$2(JsonFormat.scala:369)
	at scalapb.json4s.JsonFormat$.parsePrimitive(JsonFormat.scala:442)
	at scalapb.json4s.JsonFormat$.$anonfun$primitiveWrapperParser$1(JsonFormat.scala:369)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:288)
	at scalapb.json4s.Parser.parseSingleValue(JsonFormat.scala:322)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$2(JsonFormat.scala:280)
	at scalapb.json4s.Parser.parseValue$1(JsonFormat.scala:280)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$6(JsonFormat.scala:297)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$4(JsonFormat.scala:296)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:295)
	at scalapb.json4s.Parser.fromJson(JsonFormat.scala:244)
```
My question is: how could we make such messages (nulls in json array) valid? Introducing `OptionalString` adds additional level of nesting in array elements.

Thank you!

**Comment by thesamet** [comment]
In scalapb-json4s, you can define a custom parser and writer for message types, by creating a format registry, see https://github.com/scalapb/scalapb-json4s/blob/f934ad90e7e41e987616a8bbd198a45239a29ba8/src/main/scala/scalapb/json4s/JsonFormat.scala#L26 

It looks like you should be able to get the format that you want if you customize `OptionalString`. I am sorry that there are no usage examples outside the source code right now, - feel free to let me know if anything is unclear.

**Comment by vipo** [comment]
Thank you.
