### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by vishrantgupta** [scalapb/ScalaPB#482]
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1309)
	at com.trueaccord.scalapb.GeneratedEnum$class.javaValueDescriptor(GeneratedMessageCompanion.scala:26)

```

**Comment by thesamet** [comment]
@vishrantgupta can you provide instructions on how to reproduce this exception - an example of a proto file and a code that triggers this exception?

Based on the class name `com.trueaccord` you are using an older version of ScalaPB, can you check if this still occurs on the latest version?

**Comment by vishrantgupta** [comment]
@thesamet that is true, my company was using older version of ScalaPB to generate Scala files. This issue arises when I was trying to print the default values of ENUM types.

**Comment by thesamet** [comment]
You are most likely observing issue #225 which has been resolved a while ago. Are you able to upgrade to the latest version?

**Comment by vishrantgupta** [comment]
No that will be a big change. But will give it a try.
