### ISSUE TITLE
Still reproduce MatchError when deserializing unknown enum value

### ISSUE THREAD

**Issue by syucream** [scalapb/ScalaPB#507]
I've caught the MatchError in https://github.com/scalapb/ScalaPB/issues/285 in my environment with using ScalaPB.

And I could reproduce the error by below code.
https://github.com/syucream/scalapb-unknown-enum

```
$ date -u ; sbt "runMain Example" ; date -u
Thu Oct  4 09:29:20 UTC 2018
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/syucream/sandbox/scalapb-unknown-enum/project
[info] Loading settings from build.sbt ...
[info] Set current project to scalapb-unknown-enum (in build file:/Users/syucream/sandbox/scalapb-unknown-enum/)
[info] Running Example
[error] (run-main-0) scala.MatchError: Some(scala.ref.WeakReferenceWithWrapper@1afc4206) (of class scala.Some)
[error] scala.MatchError: Some(scala.ref.WeakReferenceWithWrapper@1afc4206) (of class scala.Some)
[error]         at scalapb.descriptors.ConcurrentWeakReferenceMap.getOrElseUpdate(ConcurrentWeakReferenceMap.scala:13)
[error]         at scalapb.descriptors.EnumDescriptor.$anonfun$findValueByNumberCreatingIfUnknown$1(Descriptor.scala:128)
[error]         at scala.Option.getOrElse(Option.scala:121)
[error]         at scalapb.descriptors.EnumDescriptor.findValueByNumberCreatingIfUnknown(Descriptor.scala:125)
[error]         at scalapb.UnrecognizedEnum.scalaValueDescriptor(GeneratedMessageCompanion.scala:47)
[error]         at scalapb.UnrecognizedEnum.scalaValueDescriptor$(GeneratedMessageCompanion.scala:46)
[error]         at example.EnumExample$EnumField$Unrecognized.scalaValueDescriptor(EnumExample.scala:147)
[error]         at Example$.main(Main.scala:8)
[error]         at Example.main(Main.scala)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.lang.reflect.Method.invoke(Method.java:498)
[error]         at sbt.Run.invokeMain(Run.scala:93)
[error]         at sbt.Run.run0(Run.scala:87)
[error]         at sbt.Run.execute$1(Run.scala:65)
[error]         at sbt.Run.$anonfun$run$4(Run.scala:77)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error]         at sbt.TrapExit$App.run(TrapExit.scala:252)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error]         at sbt.Run$.executeTrapExit(Run.scala:124)
[error]         at sbt.Run.run(Run.scala:77)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6(Defaults.scala:1163)
[error]         at sbt.Defaults$.$anonfun$bgRunMainTask$6$adapted(Defaults.scala:1158)
[error]         at sbt.internal.BackgroundThreadPool.$anonfun$run$1(DefaultBackgroundJobService.scala:366)
[error]         at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error]         at scala.util.Try$.apply(Try.scala:209)
[error]         at sbt.internal.BackgroundThreadPool$BackgroundRunnable.run(DefaultBackgroundJobService.scala:289)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 3 s, completed 2018/10/04 18:29:34
Thu Oct  4 09:29:34 UTC 2018
```

**Comment by syucream** [comment]
I think its a similar issue to https://stackoverflow.com/questions/24109126/java-racing-against-the-garbage-collector
