### ISSUE TITLE
Getting runtime exception when starting server

### ISSUE THREAD

**Issue by avnerbarr** [scalapb/ScalaPB#554]
getting this exception when starting the server and not sure what steps to take to resolve this

```
java -Dconfig.resource=dev.conf -cp /Users/avnerbarr/workspace/affinity-calculator/grpc-service/target/scala-2.12/affinity-service.jar com.dy.affinity.grpc.Service
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;CLjava/lang/Object;)V
	at io.grpc.Metadata$Key.validateName(Metadata.java:628)
	at io.grpc.Metadata$Key.<init>(Metadata.java:636)
	at io.grpc.Metadata$Key.<init>(Metadata.java:566)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:740)
	at io.grpc.Metadata$AsciiKey.<init>(Metadata.java:735)
	at io.grpc.Metadata$Key.of(Metadata.java:592)
	at io.grpc.Metadata$Key.of(Metadata.java:588)
	at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:83)
	at io.grpc.internal.AbstractServerImplBuilder.<clinit>(AbstractServerImplBuilder.java:59)
	at com.dy.affinity.grpc.Service$.delayedEndpoint$com$dy$affinity$grpc$Service$1(Service.scala:36)
	at com.dy.affinity.grpc.Service$delayedInit$body.apply(Service.scala:16)
	at scala.Function0.apply$mcV$sp(Function0.scala:34)
	at scala.Function0.apply$mcV$sp$(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at com.dy.affinity.grpc.Service$.main(Service.scala:16)
	at com.dy.affinity.grpc.Service.main(Service.scala)

```

My build.sbt looks like this:

```
lazy val grpcAffinityProviderService = project.in(file("./grpc-service")).dependsOn(provider).settings(
  commonSettings,
  name := "grpc-affinity-provider-service",
  version := "0.1.0-SNAPSHOT",
  assemblyJarName in assembly := "affinity-service.jar",
  PB.targets in Compile := Seq(
    scalapb.gen() -> (sourceManaged in Compile).value
  ),
  assemblyMergeStrategy in assembly := {
    case PathList("META-INF", xs@_*) => MergeStrategy.discard
    case PathList(ps@_*) if ps.last endsWith ".conf" => MergeStrategy.concat
    case x => MergeStrategy.first
  },
  libraryDependencies ++= Seq(
    "io.grpc" % "grpc-netty" % scalapb.compiler.Version.grpcJavaVersion,
    "io.grpc" % "grpc-services" % scalapb.compiler.Version.grpcJavaVersion,
    "com.thesamet.scalapb" %% "scalapb-runtime-grpc" % scalapb.compiler.Version.scalapbVersion,
    "com.google.guava" %
    //"com.thesamet.scalapb" %% "scalapb-runtime" % scalapb.compiler.Version.scalapbVersion % "protobuf"
  )
)
```

**Comment by thesamet** [comment]
Hi @avnerbarr , this is not a ScalaPB bug, the exception you are getting is grpc-java attempting to call a method of Guava that is not available at runtime. You are probably getting an incompatible version of Guava into the assembled fat jar. You'll need to trace what's the expected version (which depends on the version of grpc-java you are using) and which one you are getting into the jar. Try to see if a different version of Guava is somehow coming through another dependency. If you can post a minimal example project I can test locally (zip or github repo) I can try looking further.

**Comment by avnerbarr** [comment]
thanks for the quick response! I can't easily provide a test project as it is referencing an internal dependency which must be doing the damage. Is there a recommended way to force this grpc to use the correct guava ?

**Comment by thesamet** [comment]
It's hard to tell what's going on in your environment. You could produce your own shaded version of grpc-java and guava if you need to.

**Comment by avnerbarr** [comment]
can you give me apointer how to do that? I've not been successful

**Comment by avnerbarr** [comment]
https://stackoverflow.com/questions/47907446/why-isnt-guava-being-shaded-properly-in-my-build-sbt

**Comment by thesamet** [comment]
Here is an example of shading google protobuf with ScalaPB's compiler plugin: https://github.com/scalapb/ScalaPB/blob/0dbabcc175044330f130ef406812baf74b840280/build.sbt#L196

There are some details there on what JARs to include and exclude into this fatjar, and also some trick to cancel the shaded jar from depending on the non-shaded one (in L219). One thing you can try is to follow this strategy to produce your own version of grpc-java that is shipped with the right version of a shaded Guava.

Another thing to try is to get the internal dependency to use the same version of Guava.
