### ISSUE TITLE
Include json path in JsonFormatException

### ISSUE THREAD

**Issue by sttawm** [scalapb/ScalaPB#780]
When parsing json into protobuf, if a number is accidentally given for a string valued field, the following error is given. (Maybe I'm missing something, but) I would find it particularly helpful if the field name (or even better the full json path to the field) were a part of the error message!

```
scalapb.json4s.JsonFormatException: Unexpected value for StringValue
	at scalapb.json4s.JsonFormat$.$anonfun$primitiveWrapperParser$2(JsonFormat.scala:454)
	at scalapb.json4s.JsonFormat$.parsePrimitive(JsonFormat.scala:535)
	at scalapb.json4s.JsonFormat$.$anonfun$primitiveWrapperParser$1(JsonFormat.scala:454)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:361)
	at scalapb.json4s.Parser.parseSingleValue(JsonFormat.scala:403)
	at scalapb.json4s.Parser.parseValue$1(JsonFormat.scala:357)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$3(JsonFormat.scala:372)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:367)
	at scalapb.json4s.Parser.parseSingleValue(JsonFormat.scala:403)
	at scalapb.json4s.Parser.parseValue$1(JsonFormat.scala:357)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$3(JsonFormat.scala:372)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:367)
	at scalapb.json4s.Parser.parseSingleValue(JsonFormat.scala:403)
	at scalapb.json4s.Parser.parseValue$1(JsonFormat.scala:357)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$3(JsonFormat.scala:372)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:367)
	at scalapb.json4s.Parser.parseSingleValue(JsonFormat.scala:403)
	at scalapb.json4s.Parser.parseValue$1(JsonFormat.scala:357)
	at scalapb.json4s.Parser.$anonfun$fromJsonToPMessage$3(JsonFormat.scala:372)
	at scala.collection.immutable.List.foreach(List.scala:305)
	at scalapb.json4s.Parser.fromJsonToPMessage(JsonFormat.scala:367)
	at scalapb.json4s.Parser.fromJson(JsonFormat.scala:321)
	at scalapb.json4s.Parser.fromJson(JsonFormat.scala:316)
	at scalapb.json4s.Parser.fromJsonString(JsonFormat.scala:312)
	at scalapb.json4s.JsonFormat$.fromJsonString(JsonFormat.scala:471)
```

**Comment by thesamet** [comment]
Makes sense. Would you be interested in working on a PR? Sounds like the JSON path can be passed down the call stack.

**Comment by sttawm** [comment]
I don't have a date in mind but I will keep it in the back of my mind and hopefully I'll get to it eventually. Thanks for this wonderful library!

**Comment by thesamet** [comment]
Closing due to inactivity. Will be happy to get a PR for this whenever possible.
