### ISSUE TITLE
Protobuf primitive wrappers shouldn't be wrapped in a struct in the dataframe

### ISSUE THREAD

**Issue by jaina00** [scalapb/ScalaPB#798]
hi...

i am trying to read parquet files in spark...

```
import org.apache.spark.sql.{Dataset, DataFrame, functions => F}
    import glueContext.implicits.StringToColumn
    import scalapb.spark.ProtoSQL

    import scalapb.spark.Implicits._

    val res = df
        .as[CollectionOrder]
```

but getting an error

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Can't extract value from geoLocation#49.latitude: need struct type but got double;
    at org.apache.spark.sql.catalyst.expressions.ExtractValue$.apply(complexTypeExtractors.scala:73)
    at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$resolveExpression$1.applyOrElse(Analyzer.scala:1074)
    at org.apache.spark.sql.catalyst.analysis.Analyzer$$anonfun$resolveExpression$1.applyOrElse(Analyzer.scala:1065)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$2.apply(TreeNode.scala:282)
    at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$2.apply(TreeNode.scala:282)
    at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:70)
```

the proto looks like 

```
message GeoLocation {
    google.protobuf.DoubleValue latitude = 1;
    google.protobuf.DoubleValue longitude = 2;
}
```

so the issue is the primitive wrapper is getting wrapped as struct which should not happen.

This issue is happening in 09.x and 0.10.x

**Comment by thesamet** [comment]
Fixed in 0.10.2 and 0.9.2. The new behavior will be enabled by default only in 0.11.x since it would be a breaking change. See instructions on enabling it on 0.9.x/0.10.x here: https://scalapb.github.io/sparksql.html
