### ISSUE TITLE
Error when using in Spark Aggregator 

### ISSUE THREAD

**Issue by yz-ark7** [scalapb/ScalaPB#840]
I was trying to write an aggregator to merge all the fields in one message proto.

The aggregator function looks like:

```scala
package ark7.etl.aggregators

import org.apache.spark.sql.expressions.Aggregator
import com.ark7.data.user_behaviors.histories.sid_history.UserBehaviorSidHistory
import org.apache.spark.sql.Encoder
import scalapb.spark.Implicits._
import org.apache.spark.sql.Encoders

object UserBehaviorSidHistoryAggregator
    extends Aggregator[
      UserBehaviorSidHistory,
      UserBehaviorSidHistory,
      UserBehaviorSidHistory
    ] {

  override def zero: UserBehaviorSidHistory = UserBehaviorSidHistory()

  override def reduce(
      b: UserBehaviorSidHistory,
      a: UserBehaviorSidHistory
  ): UserBehaviorSidHistory = {
    merge(b, a)
  }

  override def merge(
      b1: UserBehaviorSidHistory,
      b2: UserBehaviorSidHistory
  ): UserBehaviorSidHistory = {
    b1
  }

  override def finish(
      reduction: UserBehaviorSidHistory
  ): UserBehaviorSidHistory = {
    reduction
  }

  override def bufferEncoder: Encoder[UserBehaviorSidHistory] = Encoders.product

  override def outputEncoder: Encoder[UserBehaviorSidHistory] = Encoders.product
}

```

However, I got an exception as below
```
Exception in thread "main" java.lang.AssertionError: unsafe symbol ByteString (child of package protobuf) in runtime reflection universe
        at scala.reflect.internal.Symbols$Symbol.<init>(Symbols.scala:237)
        at scala.reflect.internal.Symbols$TypeSymbol.<init>(Symbols.scala:3087)
        at scala.reflect.internal.Symbols$ClassSymbol.<init>(Symbols.scala:3273)
        at scala.reflect.internal.Symbols$StubClassSymbol.<init>(Symbols.scala:3547)
        at scala.reflect.internal.Symbols.newStubSymbol(Symbols.scala:220)
        at scala.reflect.internal.Symbols.newStubSymbol$(Symbols.scala:216)
        at scala.reflect.internal.SymbolTable.newStubSymbol(SymbolTable.scala:28)
        at scala.reflect.internal.Symbols$Symbol.newStubSymbol(Symbols.scala:540)
        at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readSymbol$6(UnPickler.scala:275)
        at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readSymbol$5(UnPickler.scala:262)
        at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readSymbol$4(UnPickler.scala:262)
        at scala.reflect.internal.pickling.UnPickler$Scan.readExtSymbol$1(UnPickler.scala:260)
        at scala.reflect.internal.pickling.UnPickler$Scan.readSymbol(UnPickler.scala:283)
        at scala.reflect.internal.pickling.UnPickler$Scan.readSymbolRef(UnPickler.scala:647)
        at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:415)
        at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readTypeRef$1(UnPickler.scala:656)
        at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:190)
        at scala.reflect.internal.pickling.UnPickler$Scan.readTypeRef(UnPickler.scala:656)
        at scala.reflect.internal.pickling.UnPickler$Scan.$anonfun$readType$1(UnPickler.scala:377)
        at scala.reflect.internal.pickling.PickleBuffer.until(PickleBuffer.scala:161)
        at scala.reflect.internal.pickling.UnPickler$Scan.readTypes$1(UnPickler.scala:375)
        at scala.reflect.internal.pickling.UnPickler$Scan.readType(UnPickler.scala:415)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.$anonfun$completeInternal$1(UnPickler.scala:724)
        at scala.reflect.internal.pickling.UnPickler$Scan.at(UnPickler.scala:190)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.completeInternal(UnPickler.scala:724)
        at scala.reflect.internal.pickling.UnPickler$Scan$LazyTypeRef.complete(UnPickler.scala:751)
        at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1548)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:227)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.info(SynchronizedSymbols.scala:227)
        at scala.reflect.internal.Symbols$SymbolContextApiImpl.typeSignature(Symbols.scala:189)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$typeSignature(SynchronizedSymbols.scala:227)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$typeSignature$1(SynchronizedSymbols.scala:161)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.typeSignature(SynchronizedSymbols.scala:149)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.typeSignature$(SynchronizedSymbols.scala:161)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.typeSignature(SynchronizedSymbols.scala:227)
        at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$14.typeSignature(SynchronizedSymbols.scala:227)
        at org.apache.spark.sql.catalyst.ScalaReflection.$anonfun$getConstructorParameters$2(ScalaReflection.scala:994)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:273)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.map(TraversableLike.scala:273)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:266)
        at scala.collection.immutable.List.map(List.scala:298)
        at org.apache.spark.sql.catalyst.ScalaReflection.getConstructorParameters(ScalaReflection.scala:993)
        at org.apache.spark.sql.catalyst.ScalaReflection.getConstructorParameters$(ScalaReflection.scala:981)
        at org.apache.spark.sql.catalyst.ScalaReflection$.getConstructorParameters(ScalaReflection.scala:49)
        at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$1(ScalaReflection.scala:647)
        at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:73)
        at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:926)
        at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:925)
        at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49)
        at org.apache.spark.sql.catalyst.ScalaReflection$.serializerFor(ScalaReflection.scala:468)
        at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$4(ScalaReflection.scala:536)
        at org.apache.spark.sql.catalyst.expressions.objects.ExternalMapToCatalyst$.apply(objects.scala:1208)
        at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$1(ScalaReflection.scala:537)
        at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:73)
        at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:926)
        at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:925)
        at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49)
        at org.apache.spark.sql.catalyst.ScalaReflection$.serializerFor(ScalaReflection.scala:468)
        at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$6(ScalaReflection.scala:660)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:280)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:280)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:277)
        at scala.collection.immutable.List.flatMap(List.scala:355)
        at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$serializerFor$1(ScalaReflection.scala:648)
        at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:73)
        at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:926)
        at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:925)
        at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49)
        at org.apache.spark.sql.catalyst.ScalaReflection$.serializerFor(ScalaReflection.scala:468)
        at org.apache.spark.sql.catalyst.ScalaReflection$.serializerFor(ScalaReflection.scala:457)
        at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$.apply(ExpressionEncoder.scala:71)
        at org.apache.spark.sql.Encoders$.product(Encoders.scala:275)
        at ark7.etl.aggregators.UserBehaviorSidHistoryAggregator$.bufferEncoder(user_behavior_sid_history_aggregator.scala:38)
        at org.apache.spark.sql.expressions.Aggregator.toColumn(Aggregator.scala:100)
        at ark7.etl.jobs.ClientUserBehaviorSessionJob$.execute(client_user_behavior_session_job.scala:69)
        at ark7.common.spark.SparkJob.main(spark_job.scala:76)
        at ark7.etl.jobs.ClientUserBehaviorSessionJob.main(client_user_behavior_session_job.scala)
```

Any clue?

**Comment by thesamet** [comment]
Yes, change `Encoders.product` in the two places into `implicitly[Encoder[UserBehaviorSidHistory]]`  - this would bring in ScalaPB's Encoders and not Spark's default.

**Comment by yz-ark7** [comment]
Thanks @thesamet , I confirmed that it works!

**Comment by yz-ark7** [comment]
Hey @thesamet , when I tried to use udf, it throws another encoder error:

```scala
val u = ProtoSQL.udf { (v: String) => UserBehaviorSidHistory() }
df.withColumn("x", u(col("sid")))
    .writeToTargetOutput()
```

```
20/06/02 22:45:57 INFO DAGScheduler: ResultStage 1 (parquet at ark_data_frame.scala:91) failed in 0.039 s due to Job aborted due to stage failure: Task not serializable: java.io.NotSerializableException: scalapb.spark.ProtoSQL$$anon$1$$anon$2
Serialization stack:
        - object not serializable (class: scalapb.spark.ProtoSQL$$anon$1$$anon$2, value: scalapb.spark.ProtoSQL$$anon$1$$anon$2@6cb8cf4d)
        - field (class: scalapb.spark.TypedEncoders$MessageTypedEncoder, name: $outer, type: interface scalapb.spark.TypedEncoders)
        - object (class scalapb.spark.TypedEncoders$MessageTypedEncoder, scalapb.spark.TypedEncoders$MessageTypedEncoder@7506d9c6)
        - field (class: frameless.functions.FramelessUdf, name: rencoder, type: class frameless.TypedEncoder)
        - object (class frameless.functions.FramelessUdf, FramelessUdf(input[1, string, true].toString))
        - element of array (index: 3)
        - array (class [Ljava.lang.Object;, size 6)
        - element of array (index: 1)
        - array (class [Ljava.lang.Object;, size 3)
        - field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
        - object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.apache.spark.sql.execution.WholeStageCodegenExec, functionalInterfaceMethod=scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic org/apache/spark/sql/execution/Wh
oleStageCodegenExec.$anonfun$doExecute$4$adapted:(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodeAndComment;[Ljava/lang/Object;Lorg/apache/spark/sql/execution/metric/SQLMetric;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, instantiatedMethodType=(Ljava/lang/Object;Lscala/collection
/Iterator;)Lscala/collection/Iterator;, numCaptured=3])
        - writeReplace data (class: java.lang.invoke.SerializedLambda)
        - object (class org.apache.spark.sql.execution.WholeStageCodegenExec$$Lambda$7779/0x0000000803037040, org.apache.spark.sql.execution.WholeStageCodegenExec$$Lambda$7779/0x0000000803037040@1c33965f)
        - element of array (index: 0)
        - array (class [Ljava.lang.Object;, size 1)
        - field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
        - object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.apache.spark.rdd.RDD, functionalInterfaceMethod=scala/Function3.apply:(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic org/apache/spark/rdd/RDD.$anonfun$mapPartit
ionsWithIndex$2$adapted:(Lscala/Function2;Lorg/apache/spark/TaskContext;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, instantiatedMethodType=(Lorg/apache/spark/TaskContext;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, numCaptured=1])
        - writeReplace data (class: java.lang.invoke.SerializedLambda)
        - object (class org.apache.spark.rdd.RDD$$Lambda$7781/0x0000000803036c40, org.apache.spark.rdd.RDD$$Lambda$7781/0x0000000803036c40@3d10ae01)
        - field (class: org.apache.spark.rdd.MapPartitionsRDD, name: f, type: interface scala.Function3)
        - object (class org.apache.spark.rdd.MapPartitionsRDD, MapPartitionsRDD[3] at parquet at ark_data_frame.scala:91)
        - field (class: scala.Tuple2, name: _1, type: class java.lang.Object)
        - object (class scala.Tuple2, (MapPartitionsRDD[3] at parquet at ark_data_frame.scala:91,org.apache.spark.sql.execution.datasources.FileFormatWriter$$$Lambda$7782/0x0000000803035840@13668e2e))
20/06/02 22:45:57 INFO DAGScheduler: Job 1 failed: parquet at ark_data_frame.scala:91, took 0.043802 s
20/06/02 22:45:57 ERROR FileFormatWriter: Aborting job 83e7fe08-8ad7-4321-a1d8-c7504ec54ab9.
org.apache.spark.SparkException: Job aborted due to stage failure: Task not serializable: java.io.NotSerializableException: scalapb.spark.ProtoSQL$$anon$1$$anon$2
Serialization stack:
        - object not serializable (class: scalapb.spark.ProtoSQL$$anon$1$$anon$2, value: scalapb.spark.ProtoSQL$$anon$1$$anon$2@6cb8cf4d)
        - field (class: scalapb.spark.TypedEncoders$MessageTypedEncoder, name: $outer, type: interface scalapb.spark.TypedEncoders)
        - object (class scalapb.spark.TypedEncoders$MessageTypedEncoder, scalapb.spark.TypedEncoders$MessageTypedEncoder@7506d9c6)
        - field (class: frameless.functions.FramelessUdf, name: rencoder, type: class frameless.TypedEncoder)
        - object (class frameless.functions.FramelessUdf, FramelessUdf(input[1, string, true].toString))
        - element of array (index: 3)
        - array (class [Ljava.lang.Object;, size 6)
        - element of array (index: 1)
        - array (class [Ljava.lang.Object;, size 3)
        - field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
        - object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.apache.spark.sql.execution.WholeStageCodegenExec, functionalInterfaceMethod=scala/Function2.apply:(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic org/apache/spark/sql/execution/Wh
oleStageCodegenExec.$anonfun$doExecute$4$adapted:(Lorg/apache/spark/sql/catalyst/expressions/codegen/CodeAndComment;[Ljava/lang/Object;Lorg/apache/spark/sql/execution/metric/SQLMetric;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, instantiatedMethodType=(Ljava/lang/Object;Lscala/collection
/Iterator;)Lscala/collection/Iterator;, numCaptured=3])
        - writeReplace data (class: java.lang.invoke.SerializedLambda)
        - object (class org.apache.spark.sql.execution.WholeStageCodegenExec$$Lambda$7779/0x0000000803037040, org.apache.spark.sql.execution.WholeStageCodegenExec$$Lambda$7779/0x0000000803037040@1c33965f)
        - element of array (index: 0)
        - array (class [Ljava.lang.Object;, size 1)
        - field (class: java.lang.invoke.SerializedLambda, name: capturedArgs, type: class [Ljava.lang.Object;)
        - object (class java.lang.invoke.SerializedLambda, SerializedLambda[capturingClass=class org.apache.spark.rdd.RDD, functionalInterfaceMethod=scala/Function3.apply:(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;, implementation=invokeStatic org/apache/spark/rdd/RDD.$anonfun$mapPartit
ionsWithIndex$2$adapted:(Lscala/Function2;Lorg/apache/spark/TaskContext;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, instantiatedMethodType=(Lorg/apache/spark/TaskContext;Ljava/lang/Object;Lscala/collection/Iterator;)Lscala/collection/Iterator;, numCaptured=1])
        - writeReplace data (class: java.lang.invoke.SerializedLambda)
        - object (class org.apache.spark.rdd.RDD$$Lambda$7781/0x0000000803036c40, org.apache.spark.rdd.RDD$$Lambda$7781/0x0000000803036c40@3d10ae01)
        - field (class: org.apache.spark.rdd.MapPartitionsRDD, name: f, type: interface scala.Function3)
        - object (class org.apache.spark.rdd.MapPartitionsRDD, MapPartitionsRDD[3] at parquet at ark_data_frame.scala:91)
        - field (class: scala.Tuple2, name: _1, type: class java.lang.Object)
        - object (class scala.Tuple2, (MapPartitionsRDD[3] at parquet at ark_data_frame.scala:91,org.apache.spark.sql.execution.datasources.FileFormatWriter$$$Lambda$7782/0x0000000803035840@13668e2e))
        at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:1891)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1879)
        at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1878)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1878)
        at org.apache.spark.scheduler.DAGScheduler.submitMissingTasks(DAGScheduler.scala:1167)
        at org.apache.spark.scheduler.DAGScheduler.submitStage(DAGScheduler.scala:1071)
        at org.apache.spark.scheduler.DAGScheduler.handleJobSubmitted(DAGScheduler.scala:1014)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2069)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2061)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2050)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:738)
        at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:167)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:170)
 ... very long stack
```

**Comment by thesamet** [comment]
Hey @yz-ark7 , it looks like you are trying to serialize a function that references something inside ProtoSQL that is not serializable (nothing there is supposed to get serialized). This can most likely be fixed by some rewrite.

Since this is unrelated to this issue, can you open a new issue and provide exact steps to reproduce?

**Comment by yz-ark7** [comment]
@thesamet Sure, I can open a new ticket if you still think it's necessary. But before that, Just a clarification that UserBehaviorSidHistory() is the same compiled protocol case class as I described in this issue early. Should be serializable, right?

**Comment by thesamet** [comment]
The case class should be serializable. The error indicates that the program attempts to serialize a different object (`scalapb.spark.ProtoSQL$$anon$1$$anon$2`), which isn't serializable.
