### ISSUE TITLE
Aggregator Serialization Error When GroupBy a Dataset

### ISSUE THREAD

**Issue by yz-ark7** [scalapb/ScalaPB#842]
Hi,

I have an Aggregator implemented:
```
object UserBehaviorSidHistoryAggregator
    extends Aggregator[
      UserBehaviorSidHistory,
      UserBehaviorSidHistory,
      UserBehaviorSidHistory,
    ] {
...
}
```

While I do the below, it works fine
```
val h = UserBehaviorSidHistoryAggregator.toColumn.name("histories")

// after a series of operations to prepare the df
df.as[UserBehaviorSidHistory]
   .select(h)
   .writeToTargetOutput()
```

But to use group by, it throws an error
```
df.as[UserBehaviorSidHistory]
  // .select(h)
  .groupBy("sid")
  .agg(h)
  .writeToTargetOutput()
```

```
java.lang.ClassCastException: class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema cannot be cast to class com.ark7.data.user_behaviors.histories.sid_history.UserBehaviorSidHistory (org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema and com.ark7.data.user_behaviors.histories.sid_history.Us
erBehaviorSidHistory are in unnamed module of loader sbt.internal.LayeredClassLoader @117365bf)
        at ark7.etl.aggregators.UserBehaviorSidHistoryAggregator$.reduce(user_behavior_sid_history_aggregator.scala:16)
        at org.apache.spark.sql.execution.aggregate.ComplexTypedAggregateExpression.update(TypedAggregateExpression.scala:242)
        at org.apache.spark.sql.catalyst.expressions.aggregate.TypedImperativeAggregate.update(interfaces.scala:532)
        at org.apache.spark.sql.execution.aggregate.AggregationIterator$$anonfun$1.$anonfun$applyOrElse$1(AggregationIterator.scala:172)
        at org.apache.spark.sql.execution.aggregate.AggregationIterator$$anonfun$1.$anonfun$applyOrElse$1$adapted(AggregationIterator.scala:172)
        at org.apache.spark.sql.execution.aggregate.AggregationIterator.$anonfun$generateProcessRow$4(AggregationIterator.scala:188)
        at org.apache.spark.sql.execution.aggregate.AggregationIterator.$anonfun$generateProcessRow$4$adapted(AggregationIterator.scala:182)
        at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.processInputs(ObjectAggregationIterator.scala:159)
        at org.apache.spark.sql.execution.aggregate.ObjectAggregationIterator.<init>(ObjectAggregationIterator.scala:78)
        at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2(ObjectHashAggregateExec.scala:127)
        at org.apache.spark.sql.execution.aggregate.ObjectHashAggregateExec.$anonfun$doExecute$2$adapted(ObjectHashAggregateExec.scala:105)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2(RDD.scala:845)
        at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsWithIndexInternal$2$adapted(RDD.scala:845)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:55)
        at org.apache.spark.scheduler.Task.run(Task.scala:123)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:830)
```

Any idea why?

**Comment by thesamet** [comment]
The problem may be inside the aggregator implementation which was not provided here. Can you add it? Also, to help saving time in reproducing this problem and fixing, it would be great if you can submit a PR with a failing test case.

**Comment by yz-ark7** [comment]
FYI, the aggregator, and okay, will do a PR.

```scala
package ark7.etl.aggregators

import ark7.common.utils.Lists
import ark7.proto.Implicits._
import com.ark7.data.user_behaviors.commons.user_device.UserDevice;
import com.ark7.data.user_behaviors.histories.sid_history.UserBehaviorSidHistory
import org.apache.spark.sql.Encoder
import org.apache.spark.sql.Encoders
import org.apache.spark.sql.expressions.Aggregator
import org.uaparser.scala.Parser
import scalapb.spark.Implicits._
import ark7.etl.libs.UserDeviceExtractor
import com.ark7.data.user_behaviors.commons.source_channel.SourceChannel
import ark7.proto.user_behaviors.ArkUserBehaviorSigHistory

object UserBehaviorSidHistoryAggregator
    extends Aggregator[
      UserBehaviorSidHistory,
      UserBehaviorSidHistory,
      UserBehaviorSidHistory,
    ] {

  override def zero: UserBehaviorSidHistory = UserBehaviorSidHistory()

  override def reduce(
      b: UserBehaviorSidHistory,
      a: UserBehaviorSidHistory,
  ): UserBehaviorSidHistory = {
    merge(b, a)
  }

  override def merge(
      b1: UserBehaviorSidHistory,
      b2: UserBehaviorSidHistory,
  ): UserBehaviorSidHistory = {
    b1
  }

  override def finish(
      his: UserBehaviorSidHistory,
  ): UserBehaviorSidHistory = {
    his
  }

  override def bufferEncoder: Encoder[UserBehaviorSidHistory] =
    implicitly[Encoder[UserBehaviorSidHistory]]

  override def outputEncoder: Encoder[UserBehaviorSidHistory] =
    implicitly[Encoder[UserBehaviorSidHistory]]
}

```

**Comment by yz-ark7** [comment]
@thesamet here's the PR: https://github.com/scalapb/sparksql-scalapb/pull/93

**Comment by yz-ark7** [comment]
@thesamet just noticed that the expected result is missing the group key in the PR, but you can still see the exception thrown out before the aggregation.

**Comment by thesamet** [comment]
> @thesamet just noticed that the expected result is missing the group key in the PR, but you can still see the exception thrown out before the aggregation.

That's fine - will look into this soon.

**Comment by yz-ark7** [comment]
@thesamet actually, I figured it out. I used the wrong group function instead.

```scala
      df.as[UserBehaviorSidHistory]
        // .select(h)
        .groupByKey(_.sid) // instead of .groupBy("sid")
        .agg(h)
        .writeToTargetOutput()
```

In the PR spec, if I made the same change, it throws out
```
[info]   java.lang.UnsupportedOperationException: Schema for type com.google.protobuf.ByteString is not supported
[info]   at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$schemaFor$1(ScalaReflection.scala:809)
[info]   at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:69)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:926)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:925)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection$.cleanUpReflectionObjects(ScalaReflection.scala:49)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection$.schemaFor(ScalaReflection.scala:740)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection$.$anonfun$schemaFor$1(ScalaReflection.scala:761)
[info]   at scala.reflect.internal.tpe.TypeConstraints$UndoLog.undo(TypeConstraints.scala:69)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects(ScalaReflection.scala:926)
[info]   at org.apache.spark.sql.catalyst.ScalaReflection.cleanUpReflectionObjects$(ScalaReflection.scala:925)
```

But I guess it's unrelated to the original issue. Sorry for the bothering :-/
